import type { LanguageCode } from '@/lib/api';

export interface LanguageOption {
  code: LanguageCode;
  /** name in its own script */
  native: string;
  /** name in English */
  english: string;
  /** BCP-47 tag for expo-speech */
  speechTag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', native: 'English', english: 'English', speechTag: 'en-IN' },
  { code: 'hi', native: 'हिन्दी', english: 'Hindi', speechTag: 'hi-IN' },
  { code: 'bn', native: 'বাংলা', english: 'Bengali', speechTag: 'bn-IN' },
  { code: 'ta', native: 'தமிழ்', english: 'Tamil', speechTag: 'ta-IN' },
  { code: 'te', native: 'తెలుగు', english: 'Telugu', speechTag: 'te-IN' },
  { code: 'mr', native: 'मराठी', english: 'Marathi', speechTag: 'mr-IN' },
  { code: 'kn', native: 'ಕನ್ನಡ', english: 'Kannada', speechTag: 'kn-IN' },
  { code: 'gu', native: 'ગુજરાતી', english: 'Gujarati', speechTag: 'gu-IN' },
  { code: 'pa', native: 'ਪੰਜਾਬੀ', english: 'Punjabi', speechTag: 'pa-IN' },
  { code: 'or', native: 'ଓଡ଼ିଆ', english: 'Odia', speechTag: 'or-IN' },
];

export function speechTagFor(code: LanguageCode): string {
  return LANGUAGES.find((l) => l.code === code)?.speechTag ?? 'hi-IN';
}

export interface Strings {
  // splash
  welcomeTitle: string;
  welcomeTagline: string;
  getStarted: string;
  // auth
  loginTab: string;
  signupTab: string;
  namePlaceholder: string;
  phonePlaceholder: string;
  passwordPlaceholder: string;
  loginBtn: string;
  signupBtn: string;
  continueGuest: string;
  authError: string;
  changeLanguageLink: string;
  // core flow
  tagline: string;
  tapToSpeak: string;
  tapHint: string;
  listening: string;
  transcribing: string;
  agentThinking: string;
  agentName: string;
  agentTapToTalk: string;
  agentHint: string;
  agentFallbackReply: string;
  clearAgent: string;
  viewResults: string;
  transcriptionError: string;
  noSpeechDetected: string;
  examplesTitle: string;
  examples: string[];
  yourSkill: string;
  nsqfMatch: string;
  matchLabel: string;
  recommended: string;
  whyThis: string;
  speakAgain: string;
  typeInstead: string;
  typePlaceholder: string;
  send: string;
  tryAgain: string;
  askAgain: string;
  changeLanguage: string;
  noConnection: string;
  noMatch: string;
  call: string;
  seats: string;
  weeks: string;
  stipendYes: string;
  // bottom nav + dashboard
  navHome: string;
  navSpeak: string;
  navPrograms: string;
  navProfile: string;
  goodMorning: string;
  goodAfternoon: string;
  goodEvening: string;
  guestLabel: string;
  homeSubtitle: string;
  speakCta: string;
  speakCtaHint: string;
  browsePrograms: string;
  programsTitle: string;
  programsSubtitle: string;
  tabTraining: string;
  searchPlaceholder: string;
  filterAll: string;
  noResults: string;
  pageOf: string;
  resultsCount: string;
  seeAll: string;
  loadingPrograms: string;
  profileTitle: string;
  guestNotice: string;
  createAccount: string;
  logout: string;
  languageLabel: string;
  phoneLabel: string;
  // confirm screen (post-speech, pre-results)
  youSaid: string;
  confirmUnderstood: string; // must contain "{skill}"
  whatNext: string;
  optionJobs: string;
  optionTraining: string;
  optionCertificate: string;
  jobsTitle: string;
  certTitle: string;
  // location
  enableLocation: string;
  enableLocationHint: string;
  locating: string;
  locationDenied: string;
  changeLocation: string;
  // onboarding (post-signup profile questions)
  onboardIntroTitle: string;
  onboardIntroBody: string;
  onboardStart: string;
  onboardSkip: string;
  stepLabel: string; // must contain "{n}"
  genderQuestion: string;
  genderMale: string;
  genderFemale: string;
  genderOther: string;
  ageQuestion: string;
  yearsSuffix: string;
  eduQuestion: string;
  eduBelow10th: string;
  edu10th: string;
  edu12th: string;
  eduIti: string;
  eduUndergrad: string;
  eduPostgrad: string;
  onboardDoneTitle: string;
  onboardDoneBody: string;
  onboardContinue: string;
  next: string;
  back: string;
  // forgot password
  forgotPassword: string;
  forgotPasswordTitle: string;
  forgotPasswordBody: string;
  otpSentNotice: string;
  devOtpNotice: string; // must contain "{otp}"
  otpPlaceholder: string;
  newPasswordPlaceholder: string;
  confirmPasswordPlaceholder: string;
  sendOtp: string;
  resetPasswordBtn: string;
  invalidOtp: string;
  passwordMismatch: string;
  photoSheetTitle: string;
  takePhoto: string;
  chooseFromLibrary: string;
  removePhoto: string;
  cancel: string;
  photoPermissionDenied: string;
  whatsappTitle: string;
  historyTitle: string;
  noHistoryYet: string;
  profileAnswerUnclear: string;
  voiceProfileIntro: string;
  voiceProfileGreeting: string;
  nameConfirmedGreeting: string;
  whatsappBody: string;
  comingSoon: string;
}

const hi: Strings = {
  welcomeTitle: 'सक्षम',
  welcomeTagline: 'अपनी भाषा में अपना हुनर बताइए और सरकारी प्रशिक्षण पाइए',
  getStarted: 'शुरू करें',
  loginTab: 'लॉग इन',
  signupTab: 'नया खाता',
  namePlaceholder: 'आपका नाम',
  phonePlaceholder: 'मोबाइल नंबर',
  passwordPlaceholder: 'पासवर्ड',
  loginBtn: 'लॉग इन करें',
  signupBtn: 'खाता बनाएं',
  continueGuest: 'बिना खाते के जारी रखें',
  authError: 'कुछ गलत हुआ, कृपया फिर से कोशिश करें',
  changeLanguageLink: 'भाषा बदलें',
  tagline: 'अपनी भाषा में अपना हुनर बताइए',
  tapToSpeak: 'बोलने के लिए दबाएँ',
  tapHint: 'अपना काम या हुनर सरल भाषा में बताइए',
  listening: 'सुन रहे हैं…',
  transcribing: 'लिख रहे हैं…',
  agentThinking: 'जवाब तैयार कर रहे हैं…',
  agentName: 'सक्षम',
  agentTapToTalk: 'एजेंट से बात करें',
  agentHint: 'अपना सवाल बोलिए, सक्षम जवाब बोलकर देगा',
  agentFallbackReply: 'मैंने आपकी बात समझ ली।',
  clearAgent: 'साफ करें',
  viewResults: 'परिणाम देखें',
  transcriptionError: 'आवाज़ को लिख नहीं पाए',
  noSpeechDetected: 'आवाज़ समझ नहीं आई, कृपया फिर से बोलें',
  examplesTitle: 'ऐसे बता सकते हैं',
  examples: [
    'मैं मिट्टी के बर्तन और मटका बनाता हूँ',
    'मैं सिलाई और कढ़ाई का काम करती हूँ',
    'मैं राज मिस्त्री हूँ, दीवार और प्लास्टर',
    'मैं गाय-भैंस पालता हूँ, दूध बेचता हूँ',
  ],
  yourSkill: 'आपने बताया',
  nsqfMatch: 'NSQF योग्यता',
  matchLabel: 'मिलान',
  recommended: 'आपके लिए प्रशिक्षण',
  whyThis: 'यह क्यों',
  speakAgain: 'फिर से सुनें',
  typeInstead: 'लिखकर बताएं',
  typePlaceholder: 'अपना हुनर यहाँ लिखें…',
  send: 'भेजें',
  tryAgain: 'दोबारा कोशिश करें',
  askAgain: 'फिर से पूछें',
  changeLanguage: 'भाषा बदलें',
  noConnection: 'सर्वर से संपर्क नहीं हो पा रहा',
  noMatch: 'हुनर पूरी तरह समझ नहीं आया — कृपया दोबारा बताइए',
  call: 'कॉल करें',
  seats: 'सीटें',
  weeks: 'सप्ताह',
  stipendYes: 'वजीफा',
  navHome: 'होम',
  navSpeak: 'बोलें',
  navPrograms: 'प्रशिक्षण',
  navProfile: 'प्रोफ़ाइल',
  goodMorning: 'सुप्रभात',
  goodAfternoon: 'नमस्कार',
  goodEvening: 'शुभ संध्या',
  guestLabel: 'साथी',
  homeSubtitle: 'अपना हुनर बताइए और सरकारी प्रशिक्षण खोजिए',
  speakCta: 'अपना हुनर बताएं',
  speakCtaHint: 'बोलकर या लिखकर बताइए',
  browsePrograms: 'सभी प्रशिक्षण देखें',
  programsTitle: 'PM-AJAY प्रशिक्षण',
  programsSubtitle: 'आपके लिए उपलब्ध कौशल प्रशिक्षण कार्यक्रम',
  tabTraining: 'प्रशिक्षण',
  searchPlaceholder: 'खोजें…',
  filterAll: 'सभी',
  noResults: 'कुछ नहीं मिला',
  pageOf: 'पृष्ठ {n} / {total}',
  resultsCount: '{n} परिणाम',
  seeAll: 'सभी देखें',
  loadingPrograms: 'लोड हो रहा है…',
  profileTitle: 'प्रोफ़ाइल',
  guestNotice: 'आप बिना खाते के उपयोग कर रहे हैं',
  createAccount: 'खाता बनाएं',
  logout: 'लॉग आउट',
  languageLabel: 'भाषा',
  phoneLabel: 'मोबाइल नंबर',
  youSaid: 'आपने कहा',
  confirmUnderstood: 'समझ गया। आपको {skill} का अनुभव है।',
  whatNext: 'आप क्या करना चाहेंगे?',
  optionJobs: 'काम / रोज़गार ढूंढना',
  optionTraining: 'ट्रेनिंग करना चाहता हूँ',
  optionCertificate: 'स्किल सर्टिफिकेट चाहिए',
  jobsTitle: 'आपके लिए रोज़गार के अवसर',
  certTitle: 'प्रमाणन के लिए प्रशिक्षण केंद्र',
  enableLocation: 'लोकेशन चालू करें',
  enableLocationHint: 'अपने पास के प्रशिक्षण कार्यक्रम खोजने के लिए',
  locating: 'लोकेशन खोज रहे हैं…',
  locationDenied: 'लोकेशन की अनुमति नहीं मिली',
  changeLocation: 'लोकेशन बदलें',
  onboardIntroTitle: 'आपको बेहतर तरीके से जानना चाहते हैं',
  onboardIntroBody: 'बस 3 छोटे सवाल — इससे हम आपके लिए सही प्रशिक्षण और योजनाएं ढूंढ पाएंगे।',
  onboardStart: 'शुरू करें',
  onboardSkip: 'अभी छोड़ें',
  stepLabel: 'चरण {n} / 3',
  genderQuestion: 'आपका लिंग?',
  genderMale: 'पुरुष',
  genderFemale: 'महिला',
  genderOther: 'अन्य',
  ageQuestion: 'आपकी उम्र?',
  yearsSuffix: 'वर्ष',
  eduQuestion: 'आप कहाँ तक पढ़े हैं?',
  eduBelow10th: '10वीं से कम',
  edu10th: '10वीं पास',
  edu12th: '12वीं पास',
  eduIti: 'आईटीआई / डिप्लोमा',
  eduUndergrad: 'स्नातक (UG)',
  eduPostgrad: 'स्नातकोत्तर (PG)',
  onboardDoneTitle: 'सब तैयार है!',
  onboardDoneBody: 'अब हम आपके लिए सही प्रशिक्षण सुझा सकते हैं।',
  onboardContinue: 'आगे बढ़ें',
  next: 'आगे',
  back: 'पीछे',
  forgotPassword: 'पासवर्ड भूल गए?',
  forgotPasswordTitle: 'पासवर्ड रीसेट करें',
  forgotPasswordBody: 'अपना मोबाइल नंबर डालें, हम आपको एक कोड भेजेंगे',
  otpSentNotice: 'नीचे कोड डालें और नया पासवर्ड बनाएं',
  devOtpNotice: 'डेमो कोड: {otp} (अभी SMS नहीं भेजा जा रहा)',
  otpPlaceholder: '6 अंकों का कोड',
  newPasswordPlaceholder: 'नया पासवर्ड',
  confirmPasswordPlaceholder: 'पासवर्ड दोबारा डालें',
  sendOtp: 'कोड भेजें',
  resetPasswordBtn: 'पासवर्ड रीसेट करें',
  invalidOtp: 'कृपया सही 6 अंकों का कोड डालें',
  passwordMismatch: 'दोनों पासवर्ड मेल नहीं खाते',
  photoSheetTitle: 'प्रोफ़ाइल फ़ोटो',
  takePhoto: 'फ़ोटो खींचें',
  chooseFromLibrary: 'गैलरी से चुनें',
  removePhoto: 'फ़ोटो हटाएं',
  cancel: 'रद्द करें',
  photoPermissionDenied: 'फ़ोटो एक्सेस की अनुमति नहीं मिली',
  whatsappTitle: 'साक्षम AI अब व्हाट्सएप पर',
  historyTitle: 'हाल की बातचीत',
  noHistoryYet: 'अभी तक कोई बातचीत नहीं',
  profileAnswerUnclear: 'मुझे समझ नहीं आया, कृपया फिर से बताएं',
  voiceProfileIntro: 'बोलकर जवाब दें, या टाइप करें',
  voiceProfileGreeting: 'नमस्ते! मैं साक्षम हूं। कृपया अपना नाम बताइए।',
  nameConfirmedGreeting: 'नमस्ते, {name}!',
  whatsappBody: 'व्हाट्सएप पर चैट करें या वॉइस नोट भेजें — ऐप की ज़रूरत नहीं',
  comingSoon: 'जल्द आ रहा है',
};

const en: Strings = {
  welcomeTitle: 'Saksham',
  welcomeTagline: 'Tell us your skill in your own language and find government training',
  getStarted: 'Get Started',
  loginTab: 'Log in',
  signupTab: 'Sign up',
  namePlaceholder: 'Your name',
  phonePlaceholder: 'Mobile number',
  passwordPlaceholder: 'Password',
  loginBtn: 'Log in',
  signupBtn: 'Create account',
  continueGuest: 'Continue without an account',
  authError: 'Something went wrong, please try again',
  changeLanguageLink: 'Change language',
  tagline: 'Tell us your skill, in your own language',
  tapToSpeak: 'Press to speak',
  tapHint: 'Describe your work or skill in simple words',
  listening: 'Listening…',
  transcribing: 'Transcribing…',
  agentThinking: 'Preparing a reply…',
  agentName: 'Saksham',
  agentTapToTalk: 'Talk to agent',
  agentHint: 'Ask your question and Saksham will answer out loud',
  agentFallbackReply: 'I understood that.',
  clearAgent: 'Clear',
  viewResults: 'View results',
  transcriptionError: 'Could not transcribe the recording',
  noSpeechDetected: 'No speech was detected. Please try again',
  examplesTitle: 'You could say',
  examples: [
    'I make clay pots and matka',
    'I do tailoring and embroidery work',
    'I am a mason, walls and plaster',
    'I rear cattle and sell milk',
  ],
  yourSkill: 'You said',
  nsqfMatch: 'NSQF qualification',
  matchLabel: 'match',
  recommended: 'Training for you',
  whyThis: 'Why this',
  speakAgain: 'Hear again',
  typeInstead: 'Type instead',
  typePlaceholder: 'Type your skill here…',
  send: 'Send',
  tryAgain: 'Try again',
  askAgain: 'Ask again',
  changeLanguage: 'Change language',
  noConnection: 'Cannot reach the server',
  noMatch: 'Could not fully understand the skill — please say it again',
  call: 'Call',
  seats: 'seats',
  weeks: 'weeks',
  stipendYes: 'Stipend',
  navHome: 'Home',
  navSpeak: 'Speak',
  navPrograms: 'Programs',
  navProfile: 'Profile',
  goodMorning: 'Good morning',
  goodAfternoon: 'Good afternoon',
  goodEvening: 'Good evening',
  guestLabel: 'there',
  homeSubtitle: 'Speak your skill and find government training',
  speakCta: 'Tell us your skill',
  speakCtaHint: 'Speak or type it in your language',
  browsePrograms: 'Browse all programmes',
  programsTitle: 'PM-AJAY Training',
  programsSubtitle: 'Skilling programmes available for you',
  tabTraining: 'Training',
  searchPlaceholder: 'Search…',
  filterAll: 'All',
  noResults: 'Nothing found',
  pageOf: 'Page {n} of {total}',
  resultsCount: '{n} results',
  seeAll: 'See all',
  loadingPrograms: 'Loading…',
  profileTitle: 'Profile',
  guestNotice: "You're using Saksham without an account",
  createAccount: 'Create an account',
  logout: 'Log out',
  languageLabel: 'Language',
  phoneLabel: 'Mobile number',
  youSaid: 'You said',
  confirmUnderstood: 'Got it. You have experience in {skill}.',
  whatNext: 'What would you like to do?',
  optionJobs: 'Find work / employment',
  optionTraining: 'I want training',
  optionCertificate: 'I want a skill certificate',
  jobsTitle: 'Employment opportunities for you',
  certTitle: 'Training centres for certification',
  enableLocation: 'Enable location',
  enableLocationHint: 'To find training programmes near you',
  locating: 'Finding your location…',
  locationDenied: 'Location permission was not granted',
  changeLocation: 'Change location',
  onboardIntroTitle: "Let's get to know you",
  onboardIntroBody: 'Just 3 quick questions — this helps us find the right training and schemes for you.',
  onboardStart: 'Start',
  onboardSkip: 'Skip for now',
  stepLabel: 'Step {n} of 3',
  genderQuestion: 'What is your gender?',
  genderMale: 'Male',
  genderFemale: 'Female',
  genderOther: 'Other',
  ageQuestion: 'What is your age?',
  yearsSuffix: 'years',
  eduQuestion: 'How far did you study?',
  eduBelow10th: 'Below 10th',
  edu10th: '10th pass',
  edu12th: '12th pass',
  eduIti: 'ITI / Diploma',
  eduUndergrad: 'Undergraduate',
  eduPostgrad: 'Postgraduate',
  onboardDoneTitle: "You're all set!",
  onboardDoneBody: 'Now we can suggest the right training for you.',
  onboardContinue: 'Continue',
  next: 'Next',
  back: 'Back',
  forgotPassword: 'Forgot password?',
  forgotPasswordTitle: 'Reset your password',
  forgotPasswordBody: "Enter your mobile number and we'll send you a code",
  otpSentNotice: 'Enter the code below and set a new password',
  devOtpNotice: 'Demo code: {otp} (no SMS is being sent right now)',
  otpPlaceholder: '6-digit code',
  newPasswordPlaceholder: 'New password',
  confirmPasswordPlaceholder: 'Confirm new password',
  sendOtp: 'Send code',
  resetPasswordBtn: 'Reset password',
  invalidOtp: 'Please enter the correct 6-digit code',
  passwordMismatch: 'Passwords do not match',
  photoSheetTitle: 'Profile photo',
  takePhoto: 'Take photo',
  chooseFromLibrary: 'Choose from gallery',
  removePhoto: 'Remove photo',
  cancel: 'Cancel',
  photoPermissionDenied: 'Permission to access photos was not granted',
  whatsappTitle: 'Saksham AI is now on WhatsApp',
  historyTitle: 'Recent conversations',
  noHistoryYet: 'No conversations yet',
  profileAnswerUnclear: "I didn't catch that, please say it again",
  voiceProfileIntro: 'Answer by speaking, or type it instead',
  voiceProfileGreeting: "Hello! I'm Saksham. Please tell me your name.",
  nameConfirmedGreeting: 'Hello, {name}!',
  whatsappBody: 'Chat or send a voice note — no app needed',
  comingSoon: 'Coming soon',
};

const bn: Strings = {
  welcomeTitle: 'সক্ষম',
  welcomeTagline: 'নিজের ভাষায় নিজের দক্ষতা বলুন এবং সরকারি প্রশিক্ষণ পান',
  getStarted: 'শুরু করুন',
  loginTab: 'লগ ইন',
  signupTab: 'নতুন অ্যাকাউন্ট',
  namePlaceholder: 'আপনার নাম',
  phonePlaceholder: 'মোবাইল নম্বর',
  passwordPlaceholder: 'পাসওয়ার্ড',
  loginBtn: 'লগ ইন করুন',
  signupBtn: 'অ্যাকাউন্ট তৈরি করুন',
  continueGuest: 'অ্যাকাউন্ট ছাড়া চালিয়ে যান',
  authError: 'কিছু ভুল হয়েছে, আবার চেষ্টা করুন',
  changeLanguageLink: 'ভাষা পরিবর্তন করুন',
  tagline: 'নিজের ভাষায় নিজের দক্ষতা বলুন',
  tapToSpeak: 'বলতে চাপ দিন',
  tapHint: 'সহজ ভাষায় আপনার কাজ বা দক্ষতা বলুন',
  listening: 'শুনছি…',
  transcribing: 'লিখছি…',
  agentThinking: 'উত্তর তৈরি হচ্ছে…',
  agentName: 'সক্ষম',
  agentTapToTalk: 'এজেন্টের সঙ্গে কথা বলুন',
  agentHint: 'আপনার প্রশ্ন বলুন, সক্ষম উত্তর শুনিয়ে দেবে',
  agentFallbackReply: 'আমি আপনার কথা বুঝেছি।',
  clearAgent: 'মুছুন',
  viewResults: 'ফলাফল দেখুন',
  transcriptionError: 'রেকর্ডিং লেখা যায়নি',
  noSpeechDetected: 'কথা বোঝা যায়নি, আবার চেষ্টা করুন',
  examplesTitle: 'এভাবে বলতে পারেন',
  examples: [
    'আমি মাটির বাসন ও কলসি বানাই',
    'আমি সেলাই ও কাঁথার কাজ করি',
    'আমি রাজমিস্ত্রি, দেওয়াল ও প্লাস্টার',
    'আমি গরু-মহিষ পালি, দুধ বিক্রি করি',
  ],
  yourSkill: 'আপনি বলেছেন',
  nsqfMatch: 'NSQF যোগ্যতা',
  matchLabel: 'মিল',
  recommended: 'আপনার জন্য প্রশিক্ষণ',
  whyThis: 'কেন এটি',
  speakAgain: 'আবার শুনুন',
  typeInstead: 'লিখে বলুন',
  typePlaceholder: 'আপনার দক্ষতা এখানে লিখুন…',
  send: 'পাঠান',
  tryAgain: 'আবার চেষ্টা করুন',
  askAgain: 'আবার জিজ্ঞাসা করুন',
  changeLanguage: 'ভাষা পরিবর্তন',
  noConnection: 'সার্ভারে পৌঁছানো যাচ্ছে না',
  noMatch: 'দক্ষতা পুরোপুরি বোঝা যায়নি — আবার বলুন',
  call: 'কল করুন',
  seats: 'আসন',
  weeks: 'সপ্তাহ',
  stipendYes: 'ভাতা',
  navHome: 'হোম',
  navSpeak: 'বলুন',
  navPrograms: 'প্রশিক্ষণ',
  navProfile: 'প্রোফাইল',
  goodMorning: 'শুভ সকাল',
  goodAfternoon: 'নমস্কার',
  goodEvening: 'শুভ সন্ধ্যা',
  guestLabel: 'বন্ধু',
  homeSubtitle: 'আপনার দক্ষতা বলুন এবং সরকারি প্রশিক্ষণ খুঁজুন',
  speakCta: 'আপনার দক্ষতা বলুন',
  speakCtaHint: 'বলে বা লিখে জানান',
  browsePrograms: 'সব প্রশিক্ষণ দেখুন',
  programsTitle: 'PM-AJAY প্রশিক্ষণ',
  programsSubtitle: 'আপনার জন্য উপলব্ধ দক্ষতা প্রশিক্ষণ কর্মসূচি',
  tabTraining: 'প্রশিক্ষণ',
  searchPlaceholder: 'খুঁজুন…',
  filterAll: 'সব',
  noResults: 'কিছু পাওয়া যায়নি',
  pageOf: 'পৃষ্ঠা {n} / {total}',
  resultsCount: '{n} ফলাফল',
  seeAll: 'সব দেখুন',
  loadingPrograms: 'লোড হচ্ছে…',
  profileTitle: 'প্রোফাইল',
  guestNotice: 'আপনি অ্যাকাউন্ট ছাড়া ব্যবহার করছেন',
  createAccount: 'অ্যাকাউন্ট তৈরি করুন',
  logout: 'লগ আউট',
  languageLabel: 'ভাষা',
  phoneLabel: 'মোবাইল নম্বর',
  youSaid: 'আপনি বলেছেন',
  confirmUnderstood: 'বুঝেছি। আপনার {skill}-এ অভিজ্ঞতা আছে।',
  whatNext: 'আপনি কী করতে চান?',
  optionJobs: 'কাজ / চাকরি খোঁজা',
  optionTraining: 'প্রশিক্ষণ নিতে চাই',
  optionCertificate: 'দক্ষতা সার্টিফিকেট চাই',
  jobsTitle: 'আপনার জন্য কর্মসংস্থানের সুযোগ',
  certTitle: 'সার্টিফিকেশনের জন্য প্রশিক্ষণ কেন্দ্র',
  enableLocation: 'লোকেশন চালু করুন',
  enableLocationHint: 'আপনার কাছাকাছি প্রশিক্ষণ কর্মসূচি খুঁজতে',
  locating: 'লোকেশন খোঁজা হচ্ছে…',
  locationDenied: 'লোকেশনের অনুমতি পাওয়া যায়নি',
  changeLocation: 'লোকেশন পরিবর্তন করুন',
  onboardIntroTitle: 'আপনাকে ভালোভাবে জানতে চাই',
  onboardIntroBody: 'মাত্র ৩টি ছোট প্রশ্ন — এতে আমরা আপনার জন্য সঠিক প্রশিক্ষণ ও প্রকল্প খুঁজে পাব।',
  onboardStart: 'শুরু করুন',
  onboardSkip: 'এখন বাদ দিন',
  stepLabel: 'ধাপ {n} / ৩',
  genderQuestion: 'আপনার লিঙ্গ?',
  genderMale: 'পুরুষ',
  genderFemale: 'মহিলা',
  genderOther: 'অন্যান্য',
  ageQuestion: 'আপনার বয়স?',
  yearsSuffix: 'বছর',
  eduQuestion: 'আপনি কত দূর পড়াশোনা করেছেন?',
  eduBelow10th: '১০ম শ্রেণীর কম',
  edu10th: '১০ম শ্রেণী পাস',
  edu12th: '১২শ শ্রেণী পাস',
  eduIti: 'আইটিআই / ডিপ্লোমা',
  eduUndergrad: 'স্নাতক (UG)',
  eduPostgrad: 'স্নাতকোত্তর (PG)',
  onboardDoneTitle: 'সব প্রস্তুত!',
  onboardDoneBody: 'এখন আমরা আপনার জন্য সঠিক প্রশিক্ষণ সুপারিশ করতে পারি।',
  onboardContinue: 'এগিয়ে যান',
  next: 'পরবর্তী',
  back: 'পিছনে',
  forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
  forgotPasswordTitle: 'পাসওয়ার্ড রিসেট করুন',
  forgotPasswordBody: 'আপনার মোবাইল নম্বর দিন, আমরা আপনাকে একটি কোড পাঠাব',
  otpSentNotice: 'নিচে কোড দিন এবং নতুন পাসওয়ার্ড তৈরি করুন',
  devOtpNotice: 'ডেমো কোড: {otp} (এখন কোনো SMS পাঠানো হচ্ছে না)',
  otpPlaceholder: '৬ সংখ্যার কোড',
  newPasswordPlaceholder: 'নতুন পাসওয়ার্ড',
  confirmPasswordPlaceholder: 'পাসওয়ার্ড আবার দিন',
  sendOtp: 'কোড পাঠান',
  resetPasswordBtn: 'পাসওয়ার্ড রিসেট করুন',
  invalidOtp: 'সঠিক ৬ সংখ্যার কোড দিন',
  passwordMismatch: 'দুটি পাসওয়ার্ড মেলেনি',
  photoSheetTitle: 'প্রোফাইল ছবি',
  takePhoto: 'ছবি তুলুন',
  chooseFromLibrary: 'গ্যালারি থেকে বেছে নিন',
  removePhoto: 'ছবি সরান',
  cancel: 'বাতিল করুন',
  photoPermissionDenied: 'ছবি অ্যাক্সেসের অনুমতি পাওয়া যায়নি',
  whatsappTitle: 'সাক্ষম AI এখন হোয়াটসঅ্যাপে',
  historyTitle: 'সাম্প্রতিক কথোপকথন',
  noHistoryYet: 'এখনও কোনো কথোপকথন নেই',
  profileAnswerUnclear: 'আমি বুঝতে পারিনি, আবার বলুন',
  voiceProfileIntro: 'বলে উত্তর দিন, অথবা টাইপ করুন',
  voiceProfileGreeting: 'নমস্কার! আমি সক্ষম। অনুগ্রহ করে আপনার নাম বলুন।',
  nameConfirmedGreeting: 'নমস্কার, {name}!',
  whatsappBody: 'চ্যাট করুন বা ভয়েস নোট পাঠান — অ্যাপের প্রয়োজন নেই',
  comingSoon: 'শীঘ্রই আসছে',
};

const ta: Strings = {
  welcomeTitle: 'சக்ஷம்',
  welcomeTagline: 'உங்கள் மொழியில் உங்கள் திறனைச் சொல்லி அரசு பயிற்சி பெறுங்கள்',
  getStarted: 'தொடங்குங்கள்',
  loginTab: 'உள்நுழைய',
  signupTab: 'புதிய கணக்கு',
  namePlaceholder: 'உங்கள் பெயர்',
  phonePlaceholder: 'மொபைல் எண்',
  passwordPlaceholder: 'கடவுச்சொல்',
  loginBtn: 'உள்நுழையவும்',
  signupBtn: 'கணக்கு உருவாக்கவும்',
  continueGuest: 'கணக்கு இல்லாமல் தொடரவும்',
  authError: 'ஏதோ தவறு நடந்தது, மீண்டும் முயற்சிக்கவும்',
  changeLanguageLink: 'மொழியை மாற்று',
  tagline: 'உங்கள் மொழியில் உங்கள் திறனைச் சொல்லுங்கள்',
  tapToSpeak: 'பேச அழுத்தவும்',
  tapHint: 'உங்கள் வேலை அல்லது திறனை எளிய வார்த்தைகளில் சொல்லுங்கள்',
  listening: 'கேட்கிறோம்…',
  transcribing: 'எழுதுகிறோம்…',
  agentThinking: 'பதில் தயார் செய்கிறோம்…',
  agentName: 'சக்ஷம்',
  agentTapToTalk: 'முகவரிடம் பேசுங்கள்',
  agentHint: 'உங்கள் கேள்வியை பேசுங்கள், சக்ஷம் பதிலை கூறும்',
  agentFallbackReply: 'உங்கள் பேச்சை புரிந்துகொண்டேன்.',
  clearAgent: 'அழி',
  viewResults: 'முடிவுகள்',
  transcriptionError: 'பதிவை உரையாக்க முடியவில்லை',
  noSpeechDetected: 'பேச்சு புரியவில்லை. மீண்டும் முயற்சிக்கவும்',
  examplesTitle: 'இப்படிச் சொல்லலாம்',
  examples: [
    'நான் மண் பானைகள் செய்கிறேன்',
    'நான் தையல் மற்றும் எம்பிராய்டரி வேலை செய்கிறேன்',
    'நான் கொத்தனார், சுவர் மற்றும் பிளாஸ்டர்',
    'நான் மாடு வளர்த்து பால் விற்கிறேன்',
  ],
  yourSkill: 'நீங்கள் சொன்னது',
  nsqfMatch: 'NSQF தகுதி',
  matchLabel: 'பொருத்தம்',
  recommended: 'உங்களுக்கான பயிற்சி',
  whyThis: 'ஏன் இது',
  speakAgain: 'மீண்டும் கேட்க',
  typeInstead: 'தட்டச்சு செய்யவும்',
  typePlaceholder: 'உங்கள் திறனை இங்கே தட்டச்சு செய்யவும்…',
  send: 'அனுப்பு',
  tryAgain: 'மீண்டும் முயற்சி',
  askAgain: 'மீண்டும் கேள்',
  changeLanguage: 'மொழியை மாற்று',
  noConnection: 'சேவையகத்தை அணுக முடியவில்லை',
  noMatch: 'திறன் முழுமையாகப் புரியவில்லை — மீண்டும் சொல்லுங்கள்',
  call: 'அழைக்கவும்',
  seats: 'இடங்கள்',
  weeks: 'வாரங்கள்',
  stipendYes: 'உதவித்தொகை',
  navHome: 'முகப்பு',
  navSpeak: 'பேசுங்கள்',
  navPrograms: 'பயிற்சி',
  navProfile: 'சுயவிவரம்',
  goodMorning: 'காலை வணக்கம்',
  goodAfternoon: 'வணக்கம்',
  goodEvening: 'மாலை வணக்கம்',
  guestLabel: 'நண்பரே',
  homeSubtitle: 'உங்கள் திறனைச் சொல்லி அரசு பயிற்சியைக் கண்டறியுங்கள்',
  speakCta: 'உங்கள் திறனைச் சொல்லுங்கள்',
  speakCtaHint: 'பேசி அல்லது தட்டச்சு செய்து சொல்லுங்கள்',
  browsePrograms: 'அனைத்து பயிற்சிகளையும் காண்க',
  programsTitle: 'PM-AJAY பயிற்சி',
  programsSubtitle: 'உங்களுக்கு கிடைக்கும் திறன் பயிற்சி திட்டங்கள்',
  tabTraining: 'பயிற்சி',
  searchPlaceholder: 'தேடு…',
  filterAll: 'அனைத்தும்',
  noResults: 'எதுவும் கிடைக்கவில்லை',
  pageOf: 'பக்கம் {n} / {total}',
  resultsCount: '{n} முடிவுகள்',
  seeAll: 'அனைத்தையும் காண்க',
  loadingPrograms: 'ஏற்றுகிறது…',
  profileTitle: 'சுயவிவரம்',
  guestNotice: 'நீங்கள் கணக்கு இல்லாமல் பயன்படுத்துகிறீர்கள்',
  createAccount: 'கணக்கு உருவாக்கவும்',
  logout: 'வெளியேறு',
  languageLabel: 'மொழி',
  phoneLabel: 'மொபைல் எண்',
  youSaid: 'நீங்கள் சொன்னது',
  confirmUnderstood: 'புரிந்தது. உங்களுக்கு {skill} அனுபவம் உள்ளது.',
  whatNext: 'நீங்கள் என்ன செய்ய விரும்புகிறீர்கள்?',
  optionJobs: 'வேலை / வேலைவாய்ப்பு தேடுதல்',
  optionTraining: 'பயிற்சி பெற விரும்புகிறேன்',
  optionCertificate: 'திறன் சான்றிதழ் வேண்டும்',
  jobsTitle: 'உங்களுக்கான வேலைவாய்ப்புகள்',
  certTitle: 'சான்றிதழுக்கான பயிற்சி மையங்கள்',
  enableLocation: 'இருப்பிடத்தை இயக்கவும்',
  enableLocationHint: 'உங்களுக்கு அருகிலுள்ள பயிற்சி திட்டங்களைக் கண்டறிய',
  locating: 'இருப்பிடத்தைக் கண்டறிகிறோம்…',
  locationDenied: 'இருப்பிட அனுமதி கிடைக்கவில்லை',
  changeLocation: 'இருப்பிடத்தை மாற்று',
  onboardIntroTitle: 'உங்களை நன்கு அறிந்துகொள்ள விரும்புகிறோம்',
  onboardIntroBody: 'வெறும் 3 சிறு கேள்விகள் — இது உங்களுக்கு சரியான பயிற்சி மற்றும் திட்டங்களைக் கண்டறிய உதவும்.',
  onboardStart: 'தொடங்கு',
  onboardSkip: 'இப்போது தவிர்',
  stepLabel: 'படி {n} / 3',
  genderQuestion: 'உங்கள் பாலினம்?',
  genderMale: 'ஆண்',
  genderFemale: 'பெண்',
  genderOther: 'மற்றவை',
  ageQuestion: 'உங்கள் வயது?',
  yearsSuffix: 'ஆண்டுகள்',
  eduQuestion: 'நீங்கள் எவ்வளவு தூரம் படித்தீர்கள்?',
  eduBelow10th: '10ஆம் வகுப்புக்குக் கீழ்',
  edu10th: '10ஆம் வகுப்பு தேர்ச்சி',
  edu12th: '12ஆம் வகுப்பு தேர்ச்சி',
  eduIti: 'ஐடிஐ / டிப்ளமா',
  eduUndergrad: 'இளங்கலை (UG)',
  eduPostgrad: 'முதுகலை (PG)',
  onboardDoneTitle: 'எல்லாம் தயார்!',
  onboardDoneBody: 'இப்போது நாங்கள் உங்களுக்கு சரியான பயிற்சியை பரிந்துரைக்க முடியும்.',
  onboardContinue: 'தொடரவும்',
  next: 'அடுத்து',
  back: 'பின்',
  forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
  forgotPasswordTitle: 'கடவுச்சொல்லை மீட்டமைக்கவும்',
  forgotPasswordBody: 'உங்கள் மொபைல் எண்ணை உள்ளிடவும், நாங்கள் ஒரு குறியீட்டை அனுப்புவோம்',
  otpSentNotice: 'கீழே குறியீட்டை உள்ளிட்டு புதிய கடவுச்சொல்லை உருவாக்கவும்',
  devOtpNotice: 'டெமோ குறியீடு: {otp} (இப்போது SMS அனுப்பப்படவில்லை)',
  otpPlaceholder: '6 இலக்க குறியீடு',
  newPasswordPlaceholder: 'புதிய கடவுச்சொல்',
  confirmPasswordPlaceholder: 'கடவுச்சொல்லை மீண்டும் உள்ளிடவும்',
  sendOtp: 'குறியீட்டை அனுப்பு',
  resetPasswordBtn: 'கடவுச்சொல்லை மீட்டமைக்கவும்',
  invalidOtp: 'சரியான 6 இலக்க குறியீட்டை உள்ளிடவும்',
  passwordMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
  photoSheetTitle: 'சுயவிவரப் புகைப்படம்',
  takePhoto: 'புகைப்படம் எடுக்கவும்',
  chooseFromLibrary: 'கேலரியிலிருந்து தேர்ந்தெடுக்கவும்',
  removePhoto: 'புகைப்படத்தை அகற்று',
  cancel: 'ரத்து செய்',
  photoPermissionDenied: 'புகைப்படங்களை அணுக அனுமதி கிடைக்கவில்லை',
  whatsappTitle: 'சாக்ஷம் AI இப்போது வாட்ஸ்அப்பில்',
  historyTitle: 'சமீபத்திய உரையாடல்கள்',
  noHistoryYet: 'இதுவரை உரையாடல்கள் இல்லை',
  profileAnswerUnclear: 'எனக்கு புரியவில்லை, மீண்டும் சொல்லுங்கள்',
  voiceProfileIntro: 'பேசி பதிலளிக்கவும், அல்லது தட்டச்சு செய்யவும்',
  voiceProfileGreeting: 'வணக்கம்! நான் சாக்ஷம். தயவுசெய்து உங்கள் பெயரைச் சொல்லுங்கள்.',
  nameConfirmedGreeting: 'வணக்கம், {name}!',
  whatsappBody: 'அரட்டையடிக்கவும் அல்லது குரல் குறிப்பு அனுப்பவும் — ஆப் தேவையில்லை',
  comingSoon: 'விரைவில் வருகிறது',
};

const te: Strings = {
  welcomeTitle: 'సాక్షమ్',
  welcomeTagline: 'మీ భాషలో మీ నైపుణ్యాన్ని చెప్పండి మరియు ప్రభుత్వ శిక్షణ పొందండి',
  getStarted: 'ప్రారంభించండి',
  loginTab: 'లాగిన్',
  signupTab: 'కొత్త ఖాతా',
  namePlaceholder: 'మీ పేరు',
  phonePlaceholder: 'మొబైల్ నంబర్',
  passwordPlaceholder: 'పాస్‌వర్డ్',
  loginBtn: 'లాగిన్ చేయండి',
  signupBtn: 'ఖాతా సృష్టించండి',
  continueGuest: 'ఖాతా లేకుండా కొనసాగండి',
  authError: 'ఏదో తప్పు జరిగింది, దయచేసి మళ్లీ ప్రయత్నించండి',
  changeLanguageLink: 'భాష మార్చండి',
  tagline: 'మీ భాషలో మీ నైపుణ్యాన్ని చెప్పండి',
  tapToSpeak: 'మాట్లాడటానికి నొక్కండి',
  tapHint: 'మీ పని లేదా నైపుణ్యాన్ని సరళంగా చెప్పండి',
  listening: 'వింటున్నాం…',
  transcribing: 'లిఖితం చేస్తున్నాం…',
  agentThinking: 'సమాధానం సిద్ధం చేస్తున్నాం…',
  agentName: 'సాక్షమ్',
  agentTapToTalk: 'ఏజెంట్‌తో మాట్లాడండి',
  agentHint: 'మీ ప్రశ్నను మాట్లాడండి, సాక్షమ్ జవాబు చెబుతుంది',
  agentFallbackReply: 'మీ మాట అర్థమైంది.',
  clearAgent: 'క్లియర్',
  viewResults: 'ఫలితాలు చూడండి',
  transcriptionError: 'రికార్డింగ్‌ను లిఖితం చేయలేకపోయాం',
  noSpeechDetected: 'మాట అర్థం కాలేదు. మళ్లీ ప్రయత్నించండి',
  examplesTitle: 'ఇలా చెప్పవచ్చు',
  examples: [
    'నేను మట్టి కుండలు మరియు మట్క తయారు చేస్తాను',
    'నేను కుట్టు మరియు ఎంబ్రాయిడరీ పని చేస్తాను',
    'నేను మేస్త్రీని, గోడలు మరియు ప్లాస్టర్ పని',
    'నేను పశువులను పెంచి పాలు అమ్ముతాను',
  ],
  yourSkill: 'మీరు చెప్పింది',
  nsqfMatch: 'NSQF అర్హత',
  matchLabel: 'సరిపోలిక',
  recommended: 'మీ కోసం శిక్షణ',
  whyThis: 'ఇది ఎందుకు',
  speakAgain: 'మళ్లీ వినండి',
  typeInstead: 'బదులుగా టైప్ చేయండి',
  typePlaceholder: 'మీ నైపుణ్యాన్ని ఇక్కడ టైప్ చేయండి…',
  send: 'పంపండి',
  tryAgain: 'మళ్లీ ప్రయత్నించండి',
  askAgain: 'మళ్లీ అడగండి',
  changeLanguage: 'భాష మార్చండి',
  noConnection: 'సర్వర్‌ను చేరుకోలేకపోయాం',
  noMatch: 'నైపుణ్యం పూర్తిగా అర్థం కాలేదు — దయచేసి మళ్లీ చెప్పండి',
  call: 'కాల్ చేయండి',
  seats: 'సీట్లు',
  weeks: 'వారాలు',
  stipendYes: 'స్టైపెండ్',
  navHome: 'హోమ్',
  navSpeak: 'మాట్లాడండి',
  navPrograms: 'శిక్షణ',
  navProfile: 'ప్రొఫైల్',
  goodMorning: 'శుభోదయం',
  goodAfternoon: 'నమస్కారం',
  goodEvening: 'శుభ సాయంత్రం',
  guestLabel: 'మిత్రమా',
  homeSubtitle: 'మీ నైపుణ్యాన్ని చెప్పి ప్రభుత్వ శిక్షణను కనుగొనండి',
  speakCta: 'మీ నైపుణ్యాన్ని చెప్పండి',
  speakCtaHint: 'మాట్లాడి లేదా టైప్ చేసి చెప్పండి',
  browsePrograms: 'అన్ని శిక్షణలను చూడండి',
  programsTitle: 'PM-AJAY శిక్షణ',
  programsSubtitle: 'మీ కోసం అందుబాటులో ఉన్న నైపుణ్య శిక్షణ కార్యక్రమాలు',
  tabTraining: 'శిక్షణ',
  searchPlaceholder: 'వెతకండి…',
  filterAll: 'అన్నీ',
  noResults: 'ఏమీ దొరకలేదు',
  pageOf: 'పేజీ {n} / {total}',
  resultsCount: '{n} ఫలితాలు',
  seeAll: 'అన్నీ చూడండి',
  loadingPrograms: 'లోడ్ అవుతోంది…',
  profileTitle: 'ప్రొఫైల్',
  guestNotice: 'మీరు ఖాతా లేకుండా ఉపయోగిస్తున్నారు',
  createAccount: 'ఖాతా సృష్టించండి',
  logout: 'లాగ్ అవుట్',
  languageLabel: 'భాష',
  phoneLabel: 'మొబైల్ నంబర్',
  youSaid: 'మీరు చెప్పారు',
  confirmUnderstood: 'అర్థమైంది. మీకు {skill}లో అనుభవం ఉంది.',
  whatNext: 'మీరు ఏమి చేయాలనుకుంటున్నారు?',
  optionJobs: 'పని / ఉద్యోగం వెతకడం',
  optionTraining: 'శిక్షణ పొందాలనుకుంటున్నాను',
  optionCertificate: 'నైపుణ్య సర్టిఫికేట్ కావాలి',
  jobsTitle: 'మీ కోసం ఉద్యోగ అవకాశాలు',
  certTitle: 'సర్టిఫికేషన్ కోసం శిక్షణ కేంద్రాలు',
  enableLocation: 'లొకేషన్ ఆన్ చేయండి',
  enableLocationHint: 'మీ దగ్గరలోని శిక్షణ కార్యక్రమాలను కనుగొనడానికి',
  locating: 'లొకేషన్ కనుగొంటున్నాం…',
  locationDenied: 'లొకేషన్ అనుమతి లభించలేదు',
  changeLocation: 'లొకేషన్ మార్చండి',
  onboardIntroTitle: 'మిమ్మల్ని బాగా తెలుసుకోవాలనుకుంటున్నాం',
  onboardIntroBody: 'కేవలం 3 చిన్న ప్రశ్నలు — దీనితో మేము మీ కోసం సరైన శిక్షణ మరియు పథకాలను కనుగొనగలం.',
  onboardStart: 'ప్రారంభించండి',
  onboardSkip: 'ఇప్పుడు వదిలేయండి',
  stepLabel: 'దశ {n} / 3',
  genderQuestion: 'మీ లింగం?',
  genderMale: 'పురుషుడు',
  genderFemale: 'స్త్రీ',
  genderOther: 'ఇతర',
  ageQuestion: 'మీ వయస్సు?',
  yearsSuffix: 'సంవత్సరాలు',
  eduQuestion: 'మీరు ఎంతవరకు చదువుకున్నారు?',
  eduBelow10th: '10వ తరగతి కంటే తక్కువ',
  edu10th: '10వ తరగతి పాస్',
  edu12th: '12వ తరగతి పాస్',
  eduIti: 'ఐటీఐ / డిప్లొమా',
  eduUndergrad: 'అండర్ గ్రాడ్యుయేట్ (UG)',
  eduPostgrad: 'పోస్ట్ గ్రాడ్యుయేట్ (PG)',
  onboardDoneTitle: 'అంతా సిద్ధం!',
  onboardDoneBody: 'ఇప్పుడు మేము మీ కోసం సరైన శిక్షణను సూచించగలం.',
  onboardContinue: 'కొనసాగించండి',
  next: 'తదుపరి',
  back: 'వెనుకకు',
  forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
  forgotPasswordTitle: 'పాస్‌వర్డ్ రీసెట్ చేయండి',
  forgotPasswordBody: 'మీ మొబైల్ నంబర్ నమోదు చేయండి, మేము మీకు ఒక కోడ్ పంపుతాము',
  otpSentNotice: 'కింద కోడ్ నమోదు చేసి కొత్త పాస్‌వర్డ్ సెట్ చేయండి',
  devOtpNotice: 'డెమో కోడ్: {otp} (ఇప్పుడు SMS పంపబడటం లేదు)',
  otpPlaceholder: '6 అంకెల కోడ్',
  newPasswordPlaceholder: 'కొత్త పాస్‌వర్డ్',
  confirmPasswordPlaceholder: 'పాస్‌వర్డ్‌ని మళ్లీ నమోదు చేయండి',
  sendOtp: 'కోడ్ పంపండి',
  resetPasswordBtn: 'పాస్‌వర్డ్ రీసెట్ చేయండి',
  invalidOtp: 'సరైన 6 అంకెల కోడ్ నమోదు చేయండి',
  passwordMismatch: 'పాస్‌వర్డ్‌లు సరిపోలలేదు',
  photoSheetTitle: 'ప్రొఫైల్ ఫోటో',
  takePhoto: 'ఫోటో తీయండి',
  chooseFromLibrary: 'గ్యాలరీ నుండి ఎంచుకోండి',
  removePhoto: 'ఫోటో తొలగించండి',
  cancel: 'రద్దు చేయండి',
  photoPermissionDenied: 'ఫోటోలను యాక్సెస్ చేయడానికి అనుమతి లభించలేదు',
  whatsappTitle: 'సాక్షమ్ AI ఇప్పుడు వాట్సాప్‌లో',
  historyTitle: 'ఇటీవలి సంభాషణలు',
  noHistoryYet: 'ఇంకా సంభాషణలు లేవు',
  profileAnswerUnclear: 'నాకు అర్థం కాలేదు, దయచేసి మళ్లీ చెప్పండి',
  voiceProfileIntro: 'మాట్లాడి సమాధానం ఇవ్వండి, లేదా టైప్ చేయండి',
  voiceProfileGreeting: 'నమస్కారం! నేను సాక్షమ్. దయచేసి మీ పేరు చెప్పండి.',
  nameConfirmedGreeting: 'నమస్కారం, {name}!',
  whatsappBody: 'చాట్ చేయండి లేదా వాయిస్ నోట్ పంపండి — యాప్ అవసరం లేదు',
  comingSoon: 'త్వరలో వస్తుంది',
};

const mr: Strings = {
  welcomeTitle: 'साक्षम',
  welcomeTagline: 'तुमच्या भाषेत तुमचे कौशल्य सांगा आणि सरकारी प्रशिक्षण मिळवा',
  getStarted: 'सुरू करा',
  loginTab: 'लॉगिन',
  signupTab: 'नवीन खाते',
  namePlaceholder: 'तुमचे नाव',
  phonePlaceholder: 'मोबाईल नंबर',
  passwordPlaceholder: 'पासवर्ड',
  loginBtn: 'लॉगिन करा',
  signupBtn: 'खाते तयार करा',
  continueGuest: 'खात्याशिवाय पुढे जा',
  authError: 'काहीतरी चूक झाली, कृपया पुन्हा प्रयत्न करा',
  changeLanguageLink: 'भाषा बदला',
  tagline: 'तुमच्या भाषेत तुमचे कौशल्य सांगा',
  tapToSpeak: 'बोलण्यासाठी टॅप करा',
  tapHint: 'तुमचे काम किंवा कौशल्य सोप्या शब्दांत सांगा',
  listening: 'ऐकत आहोत…',
  transcribing: 'लिहून घेत आहोत…',
  agentThinking: 'उत्तर तयार करत आहोत…',
  agentName: 'सक्षम',
  agentTapToTalk: 'एजंटशी बोला',
  agentHint: 'तुमचा प्रश्न बोला, सक्षम उत्तर बोलून देईल',
  agentFallbackReply: 'तुमची गोष्ट समजली.',
  clearAgent: 'साफ करा',
  viewResults: 'परिणाम पहा',
  transcriptionError: 'रेकॉर्डिंग लिहून घेता आले नाही',
  noSpeechDetected: 'बोलणे समजले नाही. पुन्हा प्रयत्न करा',
  examplesTitle: 'असे सांगू शकता',
  examples: [
    'मी मातीची भांडी आणि मडकी बनवतो',
    'मी शिवणकाम आणि भरतकाम करते',
    'मी गवंडी आहे, भिंत आणि प्लास्टरचे काम करतो',
    'मी गुरे पाळतो आणि दूध विकतो',
  ],
  yourSkill: 'तुम्ही सांगितले',
  nsqfMatch: 'NSQF पात्रता',
  matchLabel: 'जुळणी',
  recommended: 'तुमच्यासाठी प्रशिक्षण',
  whyThis: 'हे का',
  speakAgain: 'पुन्हा ऐका',
  typeInstead: 'त्याऐवजी टाइप करा',
  typePlaceholder: 'तुमचे कौशल्य इथे टाइप करा…',
  send: 'पाठवा',
  tryAgain: 'पुन्हा प्रयत्न करा',
  askAgain: 'पुन्हा विचारा',
  changeLanguage: 'भाषा बदला',
  noConnection: 'सर्व्हरशी संपर्क होऊ शकला नाही',
  noMatch: 'कौशल्य पूर्णपणे समजले नाही — कृपया पुन्हा सांगा',
  call: 'कॉल करा',
  seats: 'जागा',
  weeks: 'आठवडे',
  stipendYes: 'विद्यावेतन',
  navHome: 'मुख्यपृष्ठ',
  navSpeak: 'बोला',
  navPrograms: 'प्रशिक्षण',
  navProfile: 'प्रोफाइल',
  goodMorning: 'सुप्रभात',
  goodAfternoon: 'नमस्कार',
  goodEvening: 'शुभ संध्याकाळ',
  guestLabel: 'मित्रा',
  homeSubtitle: 'तुमचे कौशल्य सांगा आणि सरकारी प्रशिक्षण शोधा',
  speakCta: 'तुमचे कौशल्य सांगा',
  speakCtaHint: 'बोलून किंवा टाइप करून सांगा',
  browsePrograms: 'सर्व प्रशिक्षणे पहा',
  programsTitle: 'PM-AJAY प्रशिक्षण',
  programsSubtitle: 'तुमच्यासाठी उपलब्ध कौशल्य प्रशिक्षण कार्यक्रम',
  tabTraining: 'प्रशिक्षण',
  searchPlaceholder: 'शोधा…',
  filterAll: 'सर्व',
  noResults: 'काहीही सापडले नाही',
  pageOf: 'पृष्ठ {n} / {total}',
  resultsCount: '{n} निकाल',
  seeAll: 'सर्व पहा',
  loadingPrograms: 'लोड होत आहे…',
  profileTitle: 'प्रोफाइल',
  guestNotice: 'तुम्ही खात्याशिवाय वापरत आहात',
  createAccount: 'खाते तयार करा',
  logout: 'लॉगआउट',
  languageLabel: 'भाषा',
  phoneLabel: 'मोबाईल नंबर',
  youSaid: 'तुम्ही म्हणालात',
  confirmUnderstood: 'समजले. तुम्हाला {skill} मध्ये अनुभव आहे.',
  whatNext: 'तुम्हाला काय करायचे आहे?',
  optionJobs: 'काम / नोकरी शोधणे',
  optionTraining: 'मला प्रशिक्षण हवे आहे',
  optionCertificate: 'मला कौशल्य प्रमाणपत्र हवे आहे',
  jobsTitle: 'तुमच्यासाठी नोकरीच्या संधी',
  certTitle: 'प्रमाणपत्रासाठी प्रशिक्षण केंद्रे',
  enableLocation: 'लोकेशन सुरू करा',
  enableLocationHint: 'तुमच्या जवळचे प्रशिक्षण कार्यक्रम शोधण्यासाठी',
  locating: 'लोकेशन शोधत आहोत…',
  locationDenied: 'लोकेशन परवानगी मिळाली नाही',
  changeLocation: 'लोकेशन बदला',
  onboardIntroTitle: 'आम्हाला तुम्हाला अधिक चांगल्या प्रकारे जाणून घ्यायचे आहे',
  onboardIntroBody: 'फक्त 3 छोटे प्रश्न — यामुळे आम्ही तुमच्यासाठी योग्य प्रशिक्षण आणि योजना शोधू शकू.',
  onboardStart: 'सुरू करा',
  onboardSkip: 'आत्ता वगळा',
  stepLabel: 'पायरी {n} / 3',
  genderQuestion: 'तुमचे लिंग?',
  genderMale: 'पुरुष',
  genderFemale: 'स्त्री',
  genderOther: 'इतर',
  ageQuestion: 'तुमचे वय?',
  yearsSuffix: 'वर्षे',
  eduQuestion: 'तुम्ही किती शिक्षण घेतले आहे?',
  eduBelow10th: '10वी पेक्षा कमी',
  edu10th: '10वी उत्तीर्ण',
  edu12th: '12वी उत्तीर्ण',
  eduIti: 'आयटीआय / डिप्लोमा',
  eduUndergrad: 'पदवीधर (UG)',
  eduPostgrad: 'पदव्युत्तर (PG)',
  onboardDoneTitle: 'सर्व तयार आहे!',
  onboardDoneBody: 'आता आम्ही तुमच्यासाठी योग्य प्रशिक्षण सुचवू शकतो.',
  onboardContinue: 'पुढे जा',
  next: 'पुढे',
  back: 'मागे',
  forgotPassword: 'पासवर्ड विसरलात?',
  forgotPasswordTitle: 'पासवर्ड रीसेट करा',
  forgotPasswordBody: 'तुमचा मोबाईल नंबर टाका, आम्ही तुम्हाला एक कोड पाठवू',
  otpSentNotice: 'खाली कोड टाका आणि नवीन पासवर्ड तयार करा',
  devOtpNotice: 'डेमो कोड: {otp} (आत्ता SMS पाठवला जात नाही)',
  otpPlaceholder: '6 अंकी कोड',
  newPasswordPlaceholder: 'नवीन पासवर्ड',
  confirmPasswordPlaceholder: 'पासवर्ड पुन्हा टाका',
  sendOtp: 'कोड पाठवा',
  resetPasswordBtn: 'पासवर्ड रीसेट करा',
  invalidOtp: 'योग्य 6 अंकी कोड टाका',
  passwordMismatch: 'दोन्ही पासवर्ड जुळत नाहीत',
  photoSheetTitle: 'प्रोफाइल फोटो',
  takePhoto: 'फोटो काढा',
  chooseFromLibrary: 'गॅलरीमधून निवडा',
  removePhoto: 'फोटो काढून टाका',
  cancel: 'रद्द करा',
  photoPermissionDenied: 'फोटो अ‍ॅक्सेस करण्याची परवानगी मिळाली नाही',
  whatsappTitle: 'साक्षम AI आता व्हॉट्सअ‍ॅपवर',
  historyTitle: 'अलीकडील संभाषणे',
  noHistoryYet: 'अजून कोणतेही संभाषण नाही',
  profileAnswerUnclear: 'मला समजले नाही, कृपया पुन्हा सांगा',
  voiceProfileIntro: 'बोलून उत्तर द्या, किंवा टाइप करा',
  voiceProfileGreeting: 'नमस्कार! मी साक्षम आहे. कृपया तुमचे नाव सांगा.',
  nameConfirmedGreeting: 'नमस्कार, {name}!',
  whatsappBody: 'चॅट करा किंवा व्हॉइस नोट पाठवा — अ‍ॅपची गरज नाही',
  comingSoon: 'लवकरच येत आहे',
};

const kn: Strings = {
  welcomeTitle: 'ಸಕ್ಷಮ್',
  welcomeTagline: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಕೌಶಲ್ಯವನ್ನು ಹೇಳಿ ಮತ್ತು ಸರ್ಕಾರಿ ತರಬೇತಿ ಪಡೆಯಿರಿ',
  getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
  loginTab: 'ಲಾಗಿನ್',
  signupTab: 'ಹೊಸ ಖಾತೆ',
  namePlaceholder: 'ನಿಮ್ಮ ಹೆಸರು',
  phonePlaceholder: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
  passwordPlaceholder: 'ಪಾಸ್‌ವರ್ಡ್',
  loginBtn: 'ಲಾಗಿನ್ ಮಾಡಿ',
  signupBtn: 'ಖಾತೆ ರಚಿಸಿ',
  continueGuest: 'ಖಾತೆ ಇಲ್ಲದೆ ಮುಂದುವರಿಸಿ',
  authError: 'ಏನೋ ತಪ್ಪಾಗಿದೆ, ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
  changeLanguageLink: 'ಭಾಷೆ ಬದಲಿಸಿ',
  tagline: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಕೌಶಲ್ಯವನ್ನು ಹೇಳಿ',
  tapToSpeak: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
  tapHint: 'ನಿಮ್ಮ ಕೆಲಸ ಅಥವಾ ಕೌಶಲ್ಯವನ್ನು ಸರಳವಾಗಿ ಹೇಳಿ',
  listening: 'ಕೇಳುತ್ತಿದ್ದೇವೆ…',
  transcribing: 'ಬರೆಯುತ್ತಿದ್ದೇವೆ…',
  agentThinking: 'ಉತ್ತರ ಸಿದ್ಧಪಡಿಸುತ್ತಿದ್ದೇವೆ…',
  agentName: 'ಸಕ್ಷಮ್',
  agentTapToTalk: 'ಏಜೆಂಟ್ ಜೊತೆ ಮಾತನಾಡಿ',
  agentHint: 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಮಾತನಾಡಿ, ಸಕ್ಷಮ್ ಉತ್ತರವನ್ನು ಹೇಳುತ್ತದೆ',
  agentFallbackReply: 'ನಿಮ್ಮ ಮಾತು ಅರ್ಥವಾಯಿತು.',
  clearAgent: 'ತೆರವುಗೊಳಿಸಿ',
  viewResults: 'ಫಲಿತಾಂಶ ನೋಡಿ',
  transcriptionError: 'ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನು ಪಠ್ಯವಾಗಿ ಮಾಡಲು ಆಗಲಿಲ್ಲ',
  noSpeechDetected: 'ಮಾತು ಅರ್ಥವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
  examplesTitle: 'ಹೀಗೆ ಹೇಳಬಹುದು',
  examples: [
    'ನಾನು ಮಣ್ಣಿನ ಪಾತ್ರೆಗಳು ಮತ್ತು ಮಡಿಕೆ ಮಾಡುತ್ತೇನೆ',
    'ನಾನು ಹೊಲಿಗೆ ಮತ್ತು ಕಸೂತಿ ಕೆಲಸ ಮಾಡುತ್ತೇನೆ',
    'ನಾನು ಮೇಸ್ತ್ರಿ, ಗೋಡೆ ಮತ್ತು ಪ್ಲಾಸ್ಟರ್ ಕೆಲಸ ಮಾಡುತ್ತೇನೆ',
    'ನಾನು ಜಾನುವಾರು ಸಾಕಿ ಹಾಲು ಮಾರುತ್ತೇನೆ',
  ],
  yourSkill: 'ನೀವು ಹೇಳಿದ್ದು',
  nsqfMatch: 'NSQF ಅರ್ಹತೆ',
  matchLabel: 'ಹೊಂದಾಣಿಕೆ',
  recommended: 'ನಿಮಗಾಗಿ ತರಬೇತಿ',
  whyThis: 'ಇದು ಏಕೆ',
  speakAgain: 'ಮತ್ತೆ ಕೇಳಿ',
  typeInstead: 'ಬದಲಿಗೆ ಟೈಪ್ ಮಾಡಿ',
  typePlaceholder: 'ನಿಮ್ಮ ಕೌಶಲ್ಯವನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ…',
  send: 'ಕಳುಹಿಸಿ',
  tryAgain: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
  askAgain: 'ಮತ್ತೆ ಕೇಳಿ',
  changeLanguage: 'ಭಾಷೆ ಬದಲಿಸಿ',
  noConnection: 'ಸರ್ವರ್ ಸಂಪರ್ಕಿಸಲು ಆಗಲಿಲ್ಲ',
  noMatch: 'ಕೌಶಲ್ಯ ಸಂಪೂರ್ಣವಾಗಿ ಅರ್ಥವಾಗಲಿಲ್ಲ — ದಯವಿಟ್ಟು ಮತ್ತೆ ಹೇಳಿ',
  call: 'ಕರೆ ಮಾಡಿ',
  seats: 'ಸೀಟುಗಳು',
  weeks: 'ವಾರಗಳು',
  stipendYes: 'ಸ್ಟೈಪೆಂಡ್',
  navHome: 'ಮುಖಪುಟ',
  navSpeak: 'ಮಾತನಾಡಿ',
  navPrograms: 'ತರಬೇತಿ',
  navProfile: 'ಪ್ರೊಫೈಲ್',
  goodMorning: 'ಶುಭೋದಯ',
  goodAfternoon: 'ನಮಸ್ಕಾರ',
  goodEvening: 'ಶುಭ ಸಂಜೆ',
  guestLabel: 'ಸ್ನೇಹಿತ',
  homeSubtitle: 'ನಿಮ್ಮ ಕೌಶಲ್ಯವನ್ನು ಹೇಳಿ ಮತ್ತು ಸರ್ಕಾರಿ ತರಬೇತಿ ಕಂಡುಹಿಡಿಯಿರಿ',
  speakCta: 'ನಿಮ್ಮ ಕೌಶಲ್ಯವನ್ನು ಹೇಳಿ',
  speakCtaHint: 'ಮಾತನಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ ಹೇಳಿ',
  browsePrograms: 'ಎಲ್ಲಾ ತರಬೇತಿಗಳನ್ನು ನೋಡಿ',
  programsTitle: 'PM-AJAY ತರಬೇತಿ',
  programsSubtitle: 'ನಿಮಗಾಗಿ ಲಭ್ಯವಿರುವ ಕೌಶಲ್ಯ ತರಬೇತಿ ಕಾರ್ಯಕ್ರಮಗಳು',
  tabTraining: 'ತರಬೇತಿ',
  searchPlaceholder: 'ಹುಡುಕಿ…',
  filterAll: 'ಎಲ್ಲಾ',
  noResults: 'ಏನೂ ಸಿಗಲಿಲ್ಲ',
  pageOf: 'ಪುಟ {n} / {total}',
  resultsCount: '{n} ಫಲಿತಾಂಶಗಳು',
  seeAll: 'ಎಲ್ಲಾ ನೋಡಿ',
  loadingPrograms: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
  profileTitle: 'ಪ್ರೊಫೈಲ್',
  guestNotice: 'ನೀವು ಖಾತೆ ಇಲ್ಲದೆ ಬಳಸುತ್ತಿದ್ದೀರಿ',
  createAccount: 'ಖಾತೆ ರಚಿಸಿ',
  logout: 'ಲಾಗ್ ಔಟ್',
  languageLabel: 'ಭಾಷೆ',
  phoneLabel: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
  youSaid: 'ನೀವು ಹೇಳಿದಿರಿ',
  confirmUnderstood: 'ಅರ್ಥವಾಯಿತು. ನಿಮಗೆ {skill}ನಲ್ಲಿ ಅನುಭವವಿದೆ.',
  whatNext: 'ನೀವು ಏನು ಮಾಡಲು ಬಯಸುತ್ತೀರಿ?',
  optionJobs: 'ಕೆಲಸ / ಉದ್ಯೋಗ ಹುಡುಕುವುದು',
  optionTraining: 'ನನಗೆ ತರಬೇತಿ ಬೇಕು',
  optionCertificate: 'ನನಗೆ ಕೌಶಲ್ಯ ಪ್ರಮಾಣಪತ್ರ ಬೇಕು',
  jobsTitle: 'ನಿಮಗಾಗಿ ಉದ್ಯೋಗ ಅವಕಾಶಗಳು',
  certTitle: 'ಪ್ರಮಾಣೀಕರಣಕ್ಕಾಗಿ ತರಬೇತಿ ಕೇಂದ್ರಗಳು',
  enableLocation: 'ಲೊಕೇಶನ್ ಆನ್ ಮಾಡಿ',
  enableLocationHint: 'ನಿಮ್ಮ ಹತ್ತಿರದ ತರಬೇತಿ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಹುಡುಕಲು',
  locating: 'ಲೊಕೇಶನ್ ಹುಡುಕುತ್ತಿದ್ದೇವೆ…',
  locationDenied: 'ಲೊಕೇಶನ್ ಅನುಮತಿ ಸಿಗಲಿಲ್ಲ',
  changeLocation: 'ಲೊಕೇಶನ್ ಬದಲಿಸಿ',
  onboardIntroTitle: 'ನಿಮ್ಮನ್ನು ಚೆನ್ನಾಗಿ ತಿಳಿದುಕೊಳ್ಳಲು ಬಯಸುತ್ತೇವೆ',
  onboardIntroBody: 'ಕೇವಲ 3 ಸಣ್ಣ ಪ್ರಶ್ನೆಗಳು — ಇದರಿಂದ ನಾವು ನಿಮಗೆ ಸೂಕ್ತವಾದ ತರಬೇತಿ ಮತ್ತು ಯೋಜನೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಬಹುದು.',
  onboardStart: 'ಪ್ರಾರಂಭಿಸಿ',
  onboardSkip: 'ಈಗ ಬಿಟ್ಟುಬಿಡಿ',
  stepLabel: 'ಹಂತ {n} / 3',
  genderQuestion: 'ನಿಮ್ಮ ಲಿಂಗ?',
  genderMale: 'ಪುರುಷ',
  genderFemale: 'ಮಹಿಳೆ',
  genderOther: 'ಇತರೆ',
  ageQuestion: 'ನಿಮ್ಮ ವಯಸ್ಸು?',
  yearsSuffix: 'ವರ್ಷಗಳು',
  eduQuestion: 'ನೀವು ಎಷ್ಟು ಓದಿದ್ದೀರಿ?',
  eduBelow10th: '10ನೇ ತರಗತಿಗಿಂತ ಕಡಿಮೆ',
  edu10th: '10ನೇ ತರಗತಿ ಪಾಸ್',
  edu12th: '12ನೇ ತರಗತಿ ಪಾಸ್',
  eduIti: 'ಐಟಿಐ / ಡಿಪ್ಲೊಮಾ',
  eduUndergrad: 'ಪದವಿ (UG)',
  eduPostgrad: 'ಸ್ನಾತಕೋತ್ತರ (PG)',
  onboardDoneTitle: 'ಎಲ್ಲವೂ ಸಿದ್ಧವಾಗಿದೆ!',
  onboardDoneBody: 'ಈಗ ನಾವು ನಿಮಗಾಗಿ ಸೂಕ್ತವಾದ ತರಬೇತಿಯನ್ನು ಸೂಚಿಸಬಹುದು.',
  onboardContinue: 'ಮುಂದುವರಿಸಿ',
  next: 'ಮುಂದೆ',
  back: 'ಹಿಂದೆ',
  forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
  forgotPasswordTitle: 'ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ',
  forgotPasswordBody: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ, ನಾವು ನಿಮಗೆ ಒಂದು ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ',
  otpSentNotice: 'ಕೆಳಗೆ ಕೋಡ್ ನಮೂದಿಸಿ ಮತ್ತು ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ',
  devOtpNotice: 'ಡೆಮೊ ಕೋಡ್: {otp} (ಈಗ SMS ಕಳುಹಿಸಲಾಗುತ್ತಿಲ್ಲ)',
  otpPlaceholder: '6 ಅಂಕಿಗಳ ಕೋಡ್',
  newPasswordPlaceholder: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
  confirmPasswordPlaceholder: 'ಪಾಸ್‌ವರ್ಡ್ ಅನ್ನು ಮತ್ತೆ ನಮೂದಿಸಿ',
  sendOtp: 'ಕೋಡ್ ಕಳುಹಿಸಿ',
  resetPasswordBtn: 'ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ',
  invalidOtp: 'ಸರಿಯಾದ 6 ಅಂಕಿಗಳ ಕೋಡ್ ನಮೂದಿಸಿ',
  passwordMismatch: 'ಎರಡು ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದುತ್ತಿಲ್ಲ',
  photoSheetTitle: 'ಪ್ರೊಫೈಲ್ ಫೋಟೋ',
  takePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
  chooseFromLibrary: 'ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ',
  removePhoto: 'ಫೋಟೋ ತೆಗೆದುಹಾಕಿ',
  cancel: 'ರದ್ದುಮಾಡಿ',
  photoPermissionDenied: 'ಫೋಟೋಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ಅನುಮತಿ ಸಿಗಲಿಲ್ಲ',
  whatsappTitle: 'ಸಕ್ಷಮ್ AI ಈಗ ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ',
  historyTitle: 'ಇತ್ತೀಚಿನ ಸಂಭಾಷಣೆಗಳು',
  noHistoryYet: 'ಇನ್ನೂ ಯಾವುದೇ ಸಂಭಾಷಣೆ ಇಲ್ಲ',
  profileAnswerUnclear: 'ನನಗೆ ಅರ್ಥವಾಗಲಿಲ್ಲ, ದಯವಿಟ್ಟು ಮತ್ತೆ ಹೇಳಿ',
  voiceProfileIntro: 'ಮಾತನಾಡಿ ಉತ್ತರಿಸಿ, ಅಥವಾ ಟೈಪ್ ಮಾಡಿ',
  voiceProfileGreeting: 'ನಮಸ್ಕಾರ! ನಾನು ಸಕ್ಷಮ್. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ಹೇಳಿ.',
  nameConfirmedGreeting: 'ನಮಸ್ಕಾರ, {name}!',
  whatsappBody: 'ಚಾಟ್ ಮಾಡಿ ಅಥವಾ ಧ್ವನಿ ಸಂದೇಶ ಕಳುಹಿಸಿ — ಆಪ್ ಅಗತ್ಯವಿಲ್ಲ',
  comingSoon: 'ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ',
};

const gu: Strings = {
  welcomeTitle: 'સક્ષમ',
  welcomeTagline: 'તમારી ભાષામાં તમારું કૌશલ્ય કહો અને સરકારી તાલીમ મેળવો',
  getStarted: 'શરૂ કરો',
  loginTab: 'લોગિન',
  signupTab: 'નવું ખાતું',
  namePlaceholder: 'તમારું નામ',
  phonePlaceholder: 'મોબાઇલ નંબર',
  passwordPlaceholder: 'પાસવર્ડ',
  loginBtn: 'લોગિન કરો',
  signupBtn: 'ખાતું બનાવો',
  continueGuest: 'ખાતા વગર આગળ વધો',
  authError: 'કંઈક ખોટું થયું, કૃપા કરી ફરી પ્રયાસ કરો',
  changeLanguageLink: 'ભાષા બદલો',
  tagline: 'તમારી ભાષામાં તમારું કૌશલ્ય કહો',
  tapToSpeak: 'બોલવા માટે ટેપ કરો',
  tapHint: 'તમારું કામ અથવા કૌશલ્ય સરળ શબ્દોમાં કહો',
  listening: 'સાંભળી રહ્યા છીએ…',
  transcribing: 'લખી રહ્યા છીએ…',
  agentThinking: 'જવાબ તૈયાર કરી રહ્યા છીએ…',
  agentName: 'સક્ષમ',
  agentTapToTalk: 'એજન્ટ સાથે વાત કરો',
  agentHint: 'તમારો પ્રશ્ન બોલો, સક્ષમ જવાબ બોલીને આપશે',
  agentFallbackReply: 'તમારી વાત સમજાઈ ગઈ.',
  clearAgent: 'સાફ કરો',
  viewResults: 'પરિણામ જુઓ',
  transcriptionError: 'રેકોર્ડિંગ લખી શક્યા નહીં',
  noSpeechDetected: 'બોલવું સમજાયું નહીં. ફરી પ્રયાસ કરો',
  examplesTitle: 'આ રીતે કહી શકો',
  examples: [
    'હું માટીના વાસણો અને મટકા બનાવું છું',
    'હું સિલાઈ અને ભરતકામ કરું છું',
    'હું કડિયો છું, દીવાલ અને પ્લાસ્ટરનું કામ કરું છું',
    'હું પશુ પાળું છું અને દૂધ વેચું છું',
  ],
  yourSkill: 'તમે કહ્યું',
  nsqfMatch: 'NSQF લાયકાત',
  matchLabel: 'મેળ',
  recommended: 'તમારા માટે તાલીમ',
  whyThis: 'આ શા માટે',
  speakAgain: 'ફરી સાંભળો',
  typeInstead: 'તેના બદલે ટાઇપ કરો',
  typePlaceholder: 'તમારું કૌશલ્ય અહીં ટાઇપ કરો…',
  send: 'મોકલો',
  tryAgain: 'ફરી પ્રયાસ કરો',
  askAgain: 'ફરી પૂછો',
  changeLanguage: 'ભાષા બદલો',
  noConnection: 'સર્વર સાથે સંપર્ક થઈ શક્યો નહીં',
  noMatch: 'કૌશલ્ય સંપૂર્ણપણે સમજાયું નહીં — કૃપા કરી ફરી કહો',
  call: 'કૉલ કરો',
  seats: 'બેઠકો',
  weeks: 'અઠવાડિયા',
  stipendYes: 'સ્ટાઇપેન્ડ',
  navHome: 'હોમ',
  navSpeak: 'બોલો',
  navPrograms: 'તાલીમ',
  navProfile: 'પ્રોફાઇલ',
  goodMorning: 'સુપ્રભાત',
  goodAfternoon: 'નમસ્તે',
  goodEvening: 'શુભ સાંજ',
  guestLabel: 'મિત્ર',
  homeSubtitle: 'તમારું કૌશલ્ય કહો અને સરકારી તાલીમ શોધો',
  speakCta: 'તમારું કૌશલ્ય કહો',
  speakCtaHint: 'બોલીને અથવા ટાઇપ કરીને કહો',
  browsePrograms: 'બધી તાલીમો જુઓ',
  programsTitle: 'PM-AJAY તાલીમ',
  programsSubtitle: 'તમારા માટે ઉપલબ્ધ કૌશલ્ય તાલીમ કાર્યક્રમો',
  tabTraining: 'તાલીમ',
  searchPlaceholder: 'શોધો…',
  filterAll: 'બધું',
  noResults: 'કંઈ મળ્યું નથી',
  pageOf: 'પૃષ્ઠ {n} / {total}',
  resultsCount: '{n} પરિણામો',
  seeAll: 'બધું જુઓ',
  loadingPrograms: 'લોડ થઈ રહ્યું છે…',
  profileTitle: 'પ્રોફાઇલ',
  guestNotice: 'તમે ખાતા વગર ઉપયોગ કરી રહ્યા છો',
  createAccount: 'ખાતું બનાવો',
  logout: 'લોગ આઉટ',
  languageLabel: 'ભાષા',
  phoneLabel: 'મોબાઇલ નંબર',
  youSaid: 'તમે કહ્યું',
  confirmUnderstood: 'સમજાયું. તમને {skill}માં અનુભવ છે.',
  whatNext: 'તમે શું કરવા માંગો છો?',
  optionJobs: 'કામ / નોકરી શોધવી',
  optionTraining: 'મારે તાલીમ જોઈએ છે',
  optionCertificate: 'મારે કૌશલ્ય પ્રમાણપત્ર જોઈએ છે',
  jobsTitle: 'તમારા માટે નોકરીની તકો',
  certTitle: 'પ્રમાણપત્ર માટે તાલીમ કેન્દ્રો',
  enableLocation: 'લોકેશન ચાલુ કરો',
  enableLocationHint: 'તમારી નજીકના તાલીમ કાર્યક્રમો શોધવા માટે',
  locating: 'લોકેશન શોધી રહ્યા છીએ…',
  locationDenied: 'લોકેશન પરવાનગી મળી નહીં',
  changeLocation: 'લોકેશન બદલો',
  onboardIntroTitle: 'અમે તમને વધુ સારી રીતે જાણવા માંગીએ છીએ',
  onboardIntroBody: 'ફક્ત 3 નાના પ્રશ્નો — આનાથી અમે તમારા માટે યોગ્ય તાલીમ અને યોજનાઓ શોધી શકીશું.',
  onboardStart: 'શરૂ કરો',
  onboardSkip: 'હમણાં છોડી દો',
  stepLabel: 'પગલું {n} / 3',
  genderQuestion: 'તમારું લિંગ?',
  genderMale: 'પુરુષ',
  genderFemale: 'સ્ત્રી',
  genderOther: 'અન્ય',
  ageQuestion: 'તમારી ઉંમર?',
  yearsSuffix: 'વર્ષ',
  eduQuestion: 'તમે કેટલું ભણ્યા છો?',
  eduBelow10th: '10મા ધોરણથી ઓછું',
  edu10th: '10મું પાસ',
  edu12th: '12મું પાસ',
  eduIti: 'આઈટીઆઈ / ડિપ્લોમા',
  eduUndergrad: 'સ્નાતક (UG)',
  eduPostgrad: 'અનુસ્નાતક (PG)',
  onboardDoneTitle: 'બધું તૈયાર છે!',
  onboardDoneBody: 'હવે અમે તમારા માટે યોગ્ય તાલીમ સૂચવી શકીએ છીએ.',
  onboardContinue: 'આગળ વધો',
  next: 'આગળ',
  back: 'પાછળ',
  forgotPassword: 'પાસવર્ડ ભૂલી ગયા?',
  forgotPasswordTitle: 'પાસવર્ડ રીસેટ કરો',
  forgotPasswordBody: 'તમારો મોબાઇલ નંબર દાખલ કરો, અમે તમને એક કોડ મોકલીશું',
  otpSentNotice: 'નીચે કોડ દાખલ કરો અને નવો પાસવર્ડ બનાવો',
  devOtpNotice: 'ડેમો કોડ: {otp} (અત્યારે SMS મોકલવામાં આવતો નથી)',
  otpPlaceholder: '6 અંકનો કોડ',
  newPasswordPlaceholder: 'નવો પાસવર્ડ',
  confirmPasswordPlaceholder: 'પાસવર્ડ ફરીથી દાખલ કરો',
  sendOtp: 'કોડ મોકલો',
  resetPasswordBtn: 'પાસવર્ડ રીસેટ કરો',
  invalidOtp: 'સાચો 6 અંકનો કોડ દાખલ કરો',
  passwordMismatch: 'બંને પાસવર્ડ મેળ ખાતા નથી',
  photoSheetTitle: 'પ્રોફાઇલ ફોટો',
  takePhoto: 'ફોટો લો',
  chooseFromLibrary: 'ગેલેરીમાંથી પસંદ કરો',
  removePhoto: 'ફોટો દૂર કરો',
  cancel: 'રદ કરો',
  photoPermissionDenied: 'ફોટો ઍક્સેસ કરવાની પરવાનગી મળી નહીં',
  whatsappTitle: 'સક્ષમ AI હવે વોટ્સએપ પર',
  historyTitle: 'તાજેતરની વાતચીતો',
  noHistoryYet: 'હજુ સુધી કોઈ વાતચીત નથી',
  profileAnswerUnclear: 'મને સમજાયું નહીં, કૃપા કરી ફરી કહો',
  voiceProfileIntro: 'બોલીને જવાબ આપો, અથવા ટાઇપ કરો',
  voiceProfileGreeting: 'નમસ્તે! હું સક્ષમ છું. કૃપા કરી તમારું નામ કહો.',
  nameConfirmedGreeting: 'નમસ્તે, {name}!',
  whatsappBody: 'ચેટ કરો અથવા વોઇસ નોટ મોકલો — ઍપની જરૂર નથી',
  comingSoon: 'જલ્દી આવી રહ્યું છે',
};

const pa: Strings = {
  welcomeTitle: 'ਸਕਸ਼ਮ',
  welcomeTagline: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਆਪਣਾ ਹੁਨਰ ਦੱਸੋ ਅਤੇ ਸਰਕਾਰੀ ਸਿਖਲਾਈ ਪਾਓ',
  getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
  loginTab: 'ਲਾਗਇਨ',
  signupTab: 'ਨਵਾਂ ਖਾਤਾ',
  namePlaceholder: 'ਤੁਹਾਡਾ ਨਾਮ',
  phonePlaceholder: 'ਮੋਬਾਈਲ ਨੰਬਰ',
  passwordPlaceholder: 'ਪਾਸਵਰਡ',
  loginBtn: 'ਲਾਗਇਨ ਕਰੋ',
  signupBtn: 'ਖਾਤਾ ਬਣਾਓ',
  continueGuest: 'ਖਾਤੇ ਤੋਂ ਬਿਨਾਂ ਜਾਰੀ ਰੱਖੋ',
  authError: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ, ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
  changeLanguageLink: 'ਭਾਸ਼ਾ ਬਦਲੋ',
  tagline: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਆਪਣਾ ਹੁਨਰ ਦੱਸੋ',
  tapToSpeak: 'ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ',
  tapHint: 'ਆਪਣਾ ਕੰਮ ਜਾਂ ਹੁਨਰ ਸੌਖੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਦੱਸੋ',
  listening: 'ਸੁਣ ਰਹੇ ਹਾਂ…',
  transcribing: 'ਲਿਖ ਰਹੇ ਹਾਂ…',
  agentThinking: 'ਜਵਾਬ ਤਿਆਰ ਕਰ ਰਹੇ ਹਾਂ…',
  agentName: 'ਸਕਸ਼ਮ',
  agentTapToTalk: 'ਏਜੰਟ ਨਾਲ ਗੱਲ ਕਰੋ',
  agentHint: 'ਆਪਣਾ ਸਵਾਲ ਬੋਲੋ, ਸਕਸ਼ਮ ਜਵਾਬ ਬੋਲ ਕੇ ਦੇਵੇਗਾ',
  agentFallbackReply: 'ਤੁਹਾਡੀ ਗੱਲ ਸਮਝ ਆ ਗਈ.',
  clearAgent: 'ਸਾਫ ਕਰੋ',
  viewResults: 'ਨਤੀਜੇ ਵੇਖੋ',
  transcriptionError: 'ਰਿਕਾਰਡਿੰਗ ਨੂੰ ਲਿਖ ਨਹੀਂ ਸਕੇ',
  noSpeechDetected: 'ਬੋਲਣਾ ਸਮਝ ਨਹੀਂ ਆਇਆ. ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
  examplesTitle: 'ਇੰਝ ਦੱਸ ਸਕਦੇ ਹੋ',
  examples: [
    'ਮੈਂ ਮਿੱਟੀ ਦੇ ਭਾਂਡੇ ਅਤੇ ਮਟਕੇ ਬਣਾਉਂਦਾ ਹਾਂ',
    'ਮੈਂ ਸਿਲਾਈ ਅਤੇ ਕਢਾਈ ਦਾ ਕੰਮ ਕਰਦੀ ਹਾਂ',
    'ਮੈਂ ਰਾਜ ਮਿਸਤਰੀ ਹਾਂ, ਕੰਧ ਅਤੇ ਪਲਾਸਟਰ ਦਾ ਕੰਮ ਕਰਦਾ ਹਾਂ',
    'ਮੈਂ ਪਸ਼ੂ ਪਾਲਦਾ ਹਾਂ ਅਤੇ ਦੁੱਧ ਵੇਚਦਾ ਹਾਂ',
  ],
  yourSkill: 'ਤੁਸੀਂ ਦੱਸਿਆ',
  nsqfMatch: 'NSQF ਯੋਗਤਾ',
  matchLabel: 'ਮੇਲ',
  recommended: 'ਤੁਹਾਡੇ ਲਈ ਸਿਖਲਾਈ',
  whyThis: 'ਇਹ ਕਿਉਂ',
  speakAgain: 'ਮੁੜ ਸੁਣੋ',
  typeInstead: 'ਇਸ ਦੀ ਬਜਾਏ ਟਾਈਪ ਕਰੋ',
  typePlaceholder: 'ਆਪਣਾ ਹੁਨਰ ਇੱਥੇ ਟਾਈਪ ਕਰੋ…',
  send: 'ਭੇਜੋ',
  tryAgain: 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
  askAgain: 'ਮੁੜ ਪੁੱਛੋ',
  changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
  noConnection: 'ਸਰਵਰ ਨਾਲ ਸੰਪਰਕ ਨਹੀਂ ਹੋ ਸਕਿਆ',
  noMatch: 'ਹੁਨਰ ਪੂਰੀ ਤਰ੍ਹਾਂ ਸਮਝ ਨਹੀਂ ਆਇਆ — ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਦੱਸੋ',
  call: 'ਕਾਲ ਕਰੋ',
  seats: 'ਸੀਟਾਂ',
  weeks: 'ਹਫ਼ਤੇ',
  stipendYes: 'ਸਟਾਈਪੈਂਡ',
  navHome: 'ਹੋਮ',
  navSpeak: 'ਬੋਲੋ',
  navPrograms: 'ਸਿਖਲਾਈ',
  navProfile: 'ਪ੍ਰੋਫਾਈਲ',
  goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ',
  goodAfternoon: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
  goodEvening: 'ਸ਼ੁਭ ਸ਼ਾਮ',
  guestLabel: 'ਦੋਸਤ',
  homeSubtitle: 'ਆਪਣਾ ਹੁਨਰ ਦੱਸੋ ਅਤੇ ਸਰਕਾਰੀ ਸਿਖਲਾਈ ਲੱਭੋ',
  speakCta: 'ਆਪਣਾ ਹੁਨਰ ਦੱਸੋ',
  speakCtaHint: 'ਬੋਲ ਕੇ ਜਾਂ ਟਾਈਪ ਕਰਕੇ ਦੱਸੋ',
  browsePrograms: 'ਸਾਰੀਆਂ ਸਿਖਲਾਈਆਂ ਵੇਖੋ',
  programsTitle: 'PM-AJAY ਸਿਖਲਾਈ',
  programsSubtitle: 'ਤੁਹਾਡੇ ਲਈ ਉਪਲਬਧ ਹੁਨਰ ਸਿਖਲਾਈ ਪ੍ਰੋਗਰਾਮ',
  tabTraining: 'ਸਿਖਲਾਈ',
  searchPlaceholder: 'ਖੋਜੋ…',
  filterAll: 'ਸਾਰੇ',
  noResults: 'ਕੁਝ ਨਹੀਂ ਮਿਲਿਆ',
  pageOf: 'ਪੰਨਾ {n} / {total}',
  resultsCount: '{n} ਨਤੀਜੇ',
  seeAll: 'ਸਾਰੇ ਵੇਖੋ',
  loadingPrograms: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…',
  profileTitle: 'ਪ੍ਰੋਫਾਈਲ',
  guestNotice: 'ਤੁਸੀਂ ਖਾਤੇ ਤੋਂ ਬਿਨਾਂ ਵਰਤ ਰਹੇ ਹੋ',
  createAccount: 'ਖਾਤਾ ਬਣਾਓ',
  logout: 'ਲਾਗਆਉਟ',
  languageLabel: 'ਭਾਸ਼ਾ',
  phoneLabel: 'ਮੋਬਾਈਲ ਨੰਬਰ',
  youSaid: 'ਤੁਸੀਂ ਕਿਹਾ',
  confirmUnderstood: 'ਸਮਝ ਆ ਗਿਆ. ਤੁਹਾਨੂੰ {skill} ਵਿੱਚ ਤਜਰਬਾ ਹੈ.',
  whatNext: 'ਤੁਸੀਂ ਕੀ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
  optionJobs: 'ਕੰਮ / ਨੌਕਰੀ ਲੱਭਣੀ',
  optionTraining: 'ਮੈਨੂੰ ਸਿਖਲਾਈ ਚਾਹੀਦੀ ਹੈ',
  optionCertificate: 'ਮੈਨੂੰ ਹੁਨਰ ਸਰਟੀਫਿਕੇਟ ਚਾਹੀਦਾ ਹੈ',
  jobsTitle: 'ਤੁਹਾਡੇ ਲਈ ਨੌਕਰੀ ਦੇ ਮੌਕੇ',
  certTitle: 'ਸਰਟੀਫਿਕੇਸ਼ਨ ਲਈ ਸਿਖਲਾਈ ਕੇਂਦਰ',
  enableLocation: 'ਲੋਕੇਸ਼ਨ ਚਾਲੂ ਕਰੋ',
  enableLocationHint: 'ਤੁਹਾਡੇ ਨੇੜੇ ਦੇ ਸਿਖਲਾਈ ਪ੍ਰੋਗਰਾਮ ਲੱਭਣ ਲਈ',
  locating: 'ਲੋਕੇਸ਼ਨ ਲੱਭ ਰਹੇ ਹਾਂ…',
  locationDenied: 'ਲੋਕੇਸ਼ਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਮਿਲੀ',
  changeLocation: 'ਲੋਕੇਸ਼ਨ ਬਦਲੋ',
  onboardIntroTitle: 'ਅਸੀਂ ਤੁਹਾਨੂੰ ਬਿਹਤਰ ਜਾਣਨਾ ਚਾਹੁੰਦੇ ਹਾਂ',
  onboardIntroBody: 'ਸਿਰਫ਼ 3 ਛੋਟੇ ਸਵਾਲ — ਇਸ ਨਾਲ ਅਸੀਂ ਤੁਹਾਡੇ ਲਈ ਸਹੀ ਸਿਖਲਾਈ ਅਤੇ ਯੋਜਨਾਵਾਂ ਲੱਭ ਸਕਾਂਗੇ।',
  onboardStart: 'ਸ਼ੁਰੂ ਕਰੋ',
  onboardSkip: 'ਹੁਣੇ ਛੱਡੋ',
  stepLabel: 'ਪੜਾਅ {n} / 3',
  genderQuestion: 'ਤੁਹਾਡਾ ਲਿੰਗ?',
  genderMale: 'ਪੁਰਸ਼',
  genderFemale: 'ਇਸਤਰੀ',
  genderOther: 'ਹੋਰ',
  ageQuestion: 'ਤੁਹਾਡੀ ਉਮਰ?',
  yearsSuffix: 'ਸਾਲ',
  eduQuestion: 'ਤੁਸੀਂ ਕਿੰਨੀ ਪੜ੍ਹਾਈ ਕੀਤੀ ਹੈ?',
  eduBelow10th: '10ਵੀਂ ਤੋਂ ਘੱਟ',
  edu10th: '10ਵੀਂ ਪਾਸ',
  edu12th: '12ਵੀਂ ਪਾਸ',
  eduIti: 'ਆਈਟੀਆਈ / ਡਿਪਲੋਮਾ',
  eduUndergrad: 'ਗ੍ਰੈਜੂਏਟ (UG)',
  eduPostgrad: 'ਪੋਸਟ ਗ੍ਰੈਜੂਏਟ (PG)',
  onboardDoneTitle: 'ਸਭ ਕੁਝ ਤਿਆਰ ਹੈ!',
  onboardDoneBody: 'ਹੁਣ ਅਸੀਂ ਤੁਹਾਡੇ ਲਈ ਸਹੀ ਸਿਖਲਾਈ ਦੀ ਸਿਫ਼ਾਰਸ਼ ਕਰ ਸਕਦੇ ਹਾਂ।',
  onboardContinue: 'ਜਾਰੀ ਰੱਖੋ',
  next: 'ਅੱਗੇ',
  back: 'ਪਿੱਛੇ',
  forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
  forgotPasswordTitle: 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਕਰੋ',
  forgotPasswordBody: 'ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ, ਅਸੀਂ ਤੁਹਾਨੂੰ ਇੱਕ ਕੋਡ ਭੇਜਾਂਗੇ',
  otpSentNotice: 'ਹੇਠਾਂ ਕੋਡ ਦਰਜ ਕਰੋ ਅਤੇ ਨਵਾਂ ਪਾਸਵਰਡ ਬਣਾਓ',
  devOtpNotice: 'ਡੈਮੋ ਕੋਡ: {otp} (ਹੁਣੇ SMS ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਰਿਹਾ)',
  otpPlaceholder: '6 ਅੰਕਾਂ ਦਾ ਕੋਡ',
  newPasswordPlaceholder: 'ਨਵਾਂ ਪਾਸਵਰਡ',
  confirmPasswordPlaceholder: 'ਪਾਸਵਰਡ ਮੁੜ ਦਰਜ ਕਰੋ',
  sendOtp: 'ਕੋਡ ਭੇਜੋ',
  resetPasswordBtn: 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਕਰੋ',
  invalidOtp: 'ਸਹੀ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਦਰਜ ਕਰੋ',
  passwordMismatch: 'ਦੋਵੇਂ ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ',
  photoSheetTitle: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ',
  takePhoto: 'ਫੋਟੋ ਖਿੱਚੋ',
  chooseFromLibrary: 'ਗੈਲਰੀ ਤੋਂ ਚੁਣੋ',
  removePhoto: 'ਫੋਟੋ ਹਟਾਓ',
  cancel: 'ਰੱਦ ਕਰੋ',
  photoPermissionDenied: 'ਫੋਟੋਆਂ ਤੱਕ ਪਹੁੰਚ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਮਿਲੀ',
  whatsappTitle: 'ਸਕਸ਼ਮ AI ਹੁਣ ਵਟਸਐਪ ਤੇ',
  historyTitle: 'ਹਾਲ ਦੀਆਂ ਗੱਲਾਂਬਾਤਾਂ',
  noHistoryYet: 'ਹਾਲੇ ਤੱਕ ਕੋਈ ਗੱਲਬਾਤ ਨਹੀਂ',
  profileAnswerUnclear: 'ਮੈਨੂੰ ਸਮਝ ਨਹੀਂ ਆਇਆ, ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਦੱਸੋ',
  voiceProfileIntro: 'ਬੋਲ ਕੇ ਜਵਾਬ ਦਿਓ, ਜਾਂ ਟਾਈਪ ਕਰੋ',
  voiceProfileGreeting: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਸਕਸ਼ਮ ਹਾਂ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਨਾਮ ਦੱਸੋ।',
  nameConfirmedGreeting: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ, {name}!',
  whatsappBody: 'ਚੈਟ ਕਰੋ ਜਾਂ ਵੌਇਸ ਨੋਟ ਭੇਜੋ — ਐਪ ਦੀ ਲੋੜ ਨਹੀਂ',
  comingSoon: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
};

const or: Strings = {
  welcomeTitle: 'ସକ୍ଷମ',
  welcomeTagline: 'ଆପଣଙ୍କ ଭାଷାରେ ଆପଣଙ୍କର ଦକ୍ଷତା କୁହନ୍ତୁ ଏବଂ ସରକାରୀ ତାଲିମ ପାଆନ୍ତୁ',
  getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
  loginTab: 'ଲଗଇନ୍',
  signupTab: 'ନୂଆ ଖାତା',
  namePlaceholder: 'ଆପଣଙ୍କ ନାମ',
  phonePlaceholder: 'ମୋବାଇଲ୍ ନମ୍ବର',
  passwordPlaceholder: 'ପାସୱାର୍ଡ',
  loginBtn: 'ଲଗଇନ୍ କରନ୍ତୁ',
  signupBtn: 'ଖାତା ତିଆରି କରନ୍ତୁ',
  continueGuest: 'ଖାତା ବିନା ଆଗକୁ ବଢ଼ନ୍ତୁ',
  authError: 'କିଛି ଭୁଲ ହୋଇଗଲା, ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
  changeLanguageLink: 'ଭାଷା ବଦଳାନ୍ତୁ',
  tagline: 'ଆପଣଙ୍କ ଭାଷାରେ ଆପଣଙ୍କର ଦକ୍ଷତା କୁହନ୍ତୁ',
  tapToSpeak: 'କହିବାକୁ ଟାପ୍ କରନ୍ତୁ',
  tapHint: 'ଆପଣଙ୍କର କାମ କିମ୍ବା ଦକ୍ଷତା ସହଜ ଭାଷାରେ କୁହନ୍ତୁ',
  listening: 'ଶୁଣୁଛୁ…',
  transcribing: 'ଲେଖୁଛୁ…',
  agentThinking: 'ଉତ୍ତର ପ୍ରସ୍ତୁତ କରୁଛୁ…',
  agentName: 'ସକ୍ଷମ',
  agentTapToTalk: 'ଏଜେଣ୍ଟ ସହ କଥା ହୁଅନ୍ତୁ',
  agentHint: 'ଆପଣଙ୍କ ପ୍ରଶ୍ନ କହନ୍ତୁ, ସକ୍ଷମ ଉତ୍ତର କହିଦେବ',
  agentFallbackReply: 'ଆପଣଙ୍କ କଥା ବୁଝିଲି।',
  clearAgent: 'ସଫା କରନ୍ତୁ',
  viewResults: 'ଫଳାଫଳ ଦେଖନ୍ତୁ',
  transcriptionError: 'ରେକର୍ଡିଂକୁ ଲେଖିପାରିଲୁ ନାହିଁ',
  noSpeechDetected: 'କଥା ବୁଝିପାରିଲୁ ନାହିଁ। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
  examplesTitle: 'ଏମିତି କହିପାରିବେ',
  examples: [
    'ମୁଁ ମାଟି ପାତ୍ର ଏବଂ ମାଠିଆ ତିଆରି କରେ',
    'ମୁଁ ସିଲେଇ ଏବଂ ବୁଟା କାମ କରେ',
    'ମୁଁ ରାଜମିସ୍ତ୍ରୀ, କାନ୍ଥ ଏବଂ ପ୍ଲାଷ୍ଟର କାମ କରେ',
    'ମୁଁ ପଶୁ ପାଳେ ଏବଂ କ୍ଷୀର ବିକ୍ରି କରେ',
  ],
  yourSkill: 'ଆପଣ କହିଲେ',
  nsqfMatch: 'NSQF ଯୋଗ୍ୟତା',
  matchLabel: 'ମେଳ',
  recommended: 'ଆପଣଙ୍କ ପାଇଁ ତାଲିମ',
  whyThis: 'ଏହା କାହିଁକି',
  speakAgain: 'ପୁଣି ଶୁଣନ୍ତୁ',
  typeInstead: 'ଏହା ପରିବର୍ତ୍ତେ ଟାଇପ୍ କରନ୍ତୁ',
  typePlaceholder: 'ଆପଣଙ୍କର ଦକ୍ଷତା ଏଠାରେ ଟାଇପ୍ କରନ୍ତୁ…',
  send: 'ପଠାନ୍ତୁ',
  tryAgain: 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
  askAgain: 'ପୁଣି ପଚାରନ୍ତୁ',
  changeLanguage: 'ଭାଷା ବଦଳାନ୍ତୁ',
  noConnection: 'ସର୍ଭର ସହ ସମ୍ପର୍କ ହୋଇପାରିଲା ନାହିଁ',
  noMatch: 'ଦକ୍ଷତା ସମ୍ପୂର୍ଣ୍ଣ ଭାବରେ ବୁଝି ହେଲା ନାହିଁ — ଦୟାକରି ପୁଣି କୁହନ୍ତୁ',
  call: 'କଲ୍ କରନ୍ତୁ',
  seats: 'ସିଟ୍',
  weeks: 'ସପ୍ତାହ',
  stipendYes: 'ଷ୍ଟାଇପେଣ୍ଡ',
  navHome: 'ହୋମ୍',
  navSpeak: 'କୁହନ୍ତୁ',
  navPrograms: 'ତାଲିମ',
  navProfile: 'ପ୍ରୋଫାଇଲ୍',
  goodMorning: 'ଶୁଭ ସକାଳ',
  goodAfternoon: 'ନମସ୍କାର',
  goodEvening: 'ଶୁଭ ସନ୍ଧ୍ୟା',
  guestLabel: 'ମିତ୍ର',
  homeSubtitle: 'ଆପଣଙ୍କର ଦକ୍ଷତା କୁହନ୍ତୁ ଏବଂ ସରକାରୀ ତାଲିମ ଖୋଜନ୍ତୁ',
  speakCta: 'ଆପଣଙ୍କର ଦକ୍ଷତା କୁହନ୍ତୁ',
  speakCtaHint: 'କହି କିମ୍ବା ଟାଇପ୍ କରି କୁହନ୍ତୁ',
  browsePrograms: 'ସମସ୍ତ ତାଲିମ ଦେଖନ୍ତୁ',
  programsTitle: 'PM-AJAY ତାଲିମ',
  programsSubtitle: 'ଆପଣଙ୍କ ପାଇଁ ଉପଲବ୍ଧ ଦକ୍ଷତା ତାଲିମ କାର୍ଯ୍ୟକ୍ରମ',
  tabTraining: 'ତାଲିମ',
  searchPlaceholder: 'ଖୋଜନ୍ତୁ…',
  filterAll: 'ସମସ୍ତ',
  noResults: 'କିଛି ମିଳିଲା ନାହିଁ',
  pageOf: 'ପୃଷ୍ଠା {n} / {total}',
  resultsCount: '{n} ଫଳାଫଳ',
  seeAll: 'ସମସ୍ତ ଦେଖନ୍ତୁ',
  loadingPrograms: 'ଲୋଡ୍ ହେଉଛି…',
  profileTitle: 'ପ୍ରୋଫାଇଲ୍',
  guestNotice: 'ଆପଣ ଖାତା ବିନା ବ୍ୟବହାର କରୁଛନ୍ତି',
  createAccount: 'ଖାତା ତିଆରି କରନ୍ତୁ',
  logout: 'ଲଗଆଉଟ୍',
  languageLabel: 'ଭାଷା',
  phoneLabel: 'ମୋବାଇଲ୍ ନମ୍ବର',
  youSaid: 'ଆପଣ କହିଲେ',
  confirmUnderstood: 'ବୁଝିଗଲି। ଆପଣଙ୍କର {skill}ରେ ଅଭିଜ୍ଞତା ଅଛି।',
  whatNext: 'ଆପଣ କଣ କରିବାକୁ ଚାହୁଁଛନ୍ତି?',
  optionJobs: 'କାମ / ଚାକିରି ଖୋଜିବା',
  optionTraining: 'ମୋତେ ତାଲିମ ଦରକାର',
  optionCertificate: 'ମୋତେ ଦକ୍ଷତା ପ୍ରମାଣପତ୍ର ଦରକାର',
  jobsTitle: 'ଆପଣଙ୍କ ପାଇଁ ଚାକିରି ସୁଯୋଗ',
  certTitle: 'ପ୍ରମାଣପତ୍ର ପାଇଁ ତାଲିମ କେନ୍ଦ୍ର',
  enableLocation: 'ଲୋକେସନ୍ ଚାଲୁ କରନ୍ତୁ',
  enableLocationHint: 'ଆପଣଙ୍କ ନିକଟସ୍ଥ ତାଲିମ କାର୍ଯ୍ୟକ୍ରମ ଖୋଜିବା ପାଇଁ',
  locating: 'ଲୋକେସନ୍ ଖୋଜୁଛୁ…',
  locationDenied: 'ଲୋକେସନ୍ ଅନୁମତି ମିଳିଲା ନାହିଁ',
  changeLocation: 'ଲୋକେସନ୍ ବଦଳାନ୍ତୁ',
  onboardIntroTitle: 'ଆମେ ଆପଣଙ୍କୁ ଭଲ ଭାବରେ ଜାଣିବାକୁ ଚାହୁଁଛୁ',
  onboardIntroBody: 'କେବଳ 3ଟି ଛୋଟ ପ୍ରଶ୍ନ — ଏହା ଦ୍ୱାରା ଆମେ ଆପଣଙ୍କ ପାଇଁ ସଠିକ୍ ତାଲିମ ଏବଂ ଯୋଜନା ଖୋଜିପାରିବୁ।',
  onboardStart: 'ଆରମ୍ଭ କରନ୍ତୁ',
  onboardSkip: 'ବର୍ତ୍ତମାନ ଛାଡ଼ନ୍ତୁ',
  stepLabel: 'ପାହାଚ {n} / 3',
  genderQuestion: 'ଆପଣଙ୍କର ଲିଙ୍ଗ?',
  genderMale: 'ପୁରୁଷ',
  genderFemale: 'ମହିଳା',
  genderOther: 'ଅନ୍ୟ',
  ageQuestion: 'ଆପଣଙ୍କର ବୟସ?',
  yearsSuffix: 'ବର୍ଷ',
  eduQuestion: 'ଆପଣ କେତେ ପଢ଼ିଛନ୍ତି?',
  eduBelow10th: '10ମ ଶ୍ରେଣୀରୁ କମ୍',
  edu10th: '10ମ ପାସ୍',
  edu12th: '12ଶ ପାସ୍',
  eduIti: 'ଆଇଟିଆଇ / ଡିପ୍ଲୋମା',
  eduUndergrad: 'ସ୍ନାତକ (UG)',
  eduPostgrad: 'ସ୍ନାତକୋତ୍ତର (PG)',
  onboardDoneTitle: 'ସବୁ ପ୍ରସ୍ତୁତ!',
  onboardDoneBody: 'ବର୍ତ୍ତମାନ ଆମେ ଆପଣଙ୍କ ପାଇଁ ସଠିକ୍ ତାଲିମ ପରାମର୍ଶ ଦେଇପାରିବୁ।',
  onboardContinue: 'ଆଗକୁ ବଢ଼ନ୍ତୁ',
  next: 'ପରବର୍ତ୍ତୀ',
  back: 'ପଛକୁ',
  forgotPassword: 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ?',
  forgotPasswordTitle: 'ପାସୱାର୍ଡ ରିସେଟ୍ କରନ୍ତୁ',
  forgotPasswordBody: 'ଆପଣଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ, ଆମେ ଆପଣଙ୍କୁ ଏକ କୋଡ୍ ପଠାଇବୁ',
  otpSentNotice: 'ତଳେ କୋଡ୍ ଦିଅନ୍ତୁ ଏବଂ ନୂଆ ପାସୱାର୍ଡ ତିଆରି କରନ୍ତୁ',
  devOtpNotice: 'ଡେମୋ କୋଡ୍: {otp} (ବର୍ତ୍ତମାନ SMS ପଠାଯାଉ ନାହିଁ)',
  otpPlaceholder: '6 ଅଙ୍କ କୋଡ୍',
  newPasswordPlaceholder: 'ନୂଆ ପାସୱାର୍ଡ',
  confirmPasswordPlaceholder: 'ପାସୱାର୍ଡ ପୁଣି ଦିଅନ୍ତୁ',
  sendOtp: 'କୋଡ୍ ପଠାନ୍ତୁ',
  resetPasswordBtn: 'ପାସୱାର୍ଡ ରିସେଟ୍ କରନ୍ତୁ',
  invalidOtp: 'ସଠିକ୍ 6 ଅଙ୍କ କୋଡ୍ ଦିଅନ୍ତୁ',
  passwordMismatch: 'ଦୁଇଟି ପାସୱାର୍ଡ ମେଳ ଖାଉ ନାହିଁ',
  photoSheetTitle: 'ପ୍ରୋଫାଇଲ୍ ଫଟୋ',
  takePhoto: 'ଫଟୋ ଉଠାନ୍ତୁ',
  chooseFromLibrary: 'ଗ୍ୟାଲେରୀରୁ ବାଛନ୍ତୁ',
  removePhoto: 'ଫଟୋ ହଟାନ୍ତୁ',
  cancel: 'ବାତିଲ୍ କରନ୍ତୁ',
  photoPermissionDenied: 'ଫଟୋ ଆକ୍ସେସ୍ ପାଇଁ ଅନୁମତି ମିଳିଲା ନାହିଁ',
  whatsappTitle: 'ସକ୍ଷମ AI ବର୍ତ୍ତମାନ ହ୍ୱାଟସଆପ୍‌ରେ',
  historyTitle: 'ସାମ୍ପ୍ରତିକ ବାର୍ତ୍ତାଳାପ',
  noHistoryYet: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ବାର୍ତ୍ତାଳାପ ନାହିଁ',
  profileAnswerUnclear: 'ମୁଁ ବୁଝିପାରିଲି ନାହିଁ, ଦୟାକରି ପୁଣି କୁହନ୍ତୁ',
  voiceProfileIntro: 'କହି ଉତ୍ତର ଦିଅନ୍ତୁ, କିମ୍ବା ଟାଇପ୍ କରନ୍ତୁ',
  voiceProfileGreeting: 'ନମସ୍କାର! ମୁଁ ସକ୍ଷମ। ଦୟାକରି ଆପଣଙ୍କ ନାମ କୁହନ୍ତୁ।',
  nameConfirmedGreeting: 'ନମସ୍କାର, {name}!',
  whatsappBody: 'ଚାଟ୍ କରନ୍ତୁ କିମ୍ବା ଭଏସ୍ ନୋଟ୍ ପଠାନ୍ତୁ — ଆପ୍ ଆବଶ୍ୟକ ନାହିଁ',
  comingSoon: 'ଶୀଘ୍ର ଆସୁଛି',
};

export const UI_STRINGS: Record<LanguageCode, Strings> = {
  hi,
  en,
  bn,
  ta,
  te,
  mr,
  kn,
  gu,
  pa,
  or,
};
