import Link from "next/link";
import type { Metadata } from "next";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms governing use of the Saksham website and beneficiary app.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12">
      <Link href="/" className="mb-8 inline-flex items-center gap-1.5 text-sm text-foreground-dim hover:text-brand">
        <ArrowLeft className="h-4 w-4" />
        Back to Saksham
      </Link>

      <h1 className="font-display text-3xl font-semibold">Terms of Service</h1>
      <p className="mt-1 text-sm text-foreground-faint">Last updated: September 2026</p>

      <div className="mt-6 rounded-2xl border border-warning/25 bg-warning-soft p-4 text-sm text-warning">
        This is a good-faith draft, not a substitute for legal review before real-world deployment.
      </div>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-foreground">
        <section>
          <h2 className="font-display text-lg font-semibold">1. What Saksham is</h2>
          <p className="mt-2 text-foreground-dim">
            Saksham is a prototype voice-first assistant that helps beneficiaries under the PM-AJAY scheme describe a
            traditional skill and find a matching NSQF qualification and nearby government training programme.
            Programme data (NSQF qualifications, PM-AJAY courses) is sourced from real government registers; some
            fields on training programmes (exact seat counts, contact numbers, batch dates) are illustrative sample
            data, as no government source currently publishes those centrally — this is disclosed on the homepage.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold">2. Not official government advice</h2>
          <p className="mt-2 text-foreground-dim">
            Qualification matches and programme recommendations are generated by an AI matching process against a
            real government dataset, but are suggestions, not guarantees of eligibility, enrolment, or certification.
            Always confirm details with the listed training provider or your local PM-AJAY office before making
            decisions based on what this assistant tells you.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold">3. Your account</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-foreground-dim">
            <li>You&apos;re responsible for keeping your password confidential.</li>
            <li>You may use the assistant as a guest without creating an account at all.</li>
            <li>You must be old enough, under your local law, to consent to the data collection described in our <Link href="/privacy" className="text-brand hover:underline">Privacy Policy</Link>.</li>
            <li>Provide accurate information where you choose to provide it — accuracy directly affects the quality of the recommendations you receive.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold">4. Acceptable use</h2>
          <p className="mt-2 text-foreground-dim">Don&apos;t use Saksham to:</p>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-foreground-dim">
            <li>Submit content that is unlawful, abusive, or impersonates another person.</li>
            <li>Attempt to overwhelm, scrape at scale, or reverse-engineer the service (including automated/scripted requests to its API endpoints beyond normal interactive use).</li>
            <li>Attempt to access another beneficiary&apos;s account or data.</li>
          </ul>
        </section>

        <section id="deletion">
          <h2 className="font-display text-lg font-semibold">5. Requesting data deletion</h2>
          <p className="mt-2 text-foreground-dim">
            This prototype does not yet have a self-service &quot;delete my account&quot; button in the product
            itself — that requires a change on the backend service that stores account data, which is outside this
            website&apos;s codebase. Until that exists, you can request deletion by contacting the programme
            administrator with the phone number associated with your account; we aim to action deletion requests
            within a reasonable time and will confirm once complete. We are noting this gap openly rather than
            claiming a capability that doesn&apos;t exist yet.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold">6. No warranty</h2>
          <p className="mt-2 text-foreground-dim">
            This is prototype software provided as-is, for demonstration of the PM-AJAY skilling concept. It may be
            unavailable, incomplete, or contain errors, including in AI-generated matches and translations. We make
            reasonable efforts to keep the underlying government datasets accurate and up to date but do not
            guarantee completeness or real-time accuracy.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold">7. Changes</h2>
          <p className="mt-2 text-foreground-dim">
            We may update these terms as the product evolves. Continued use after a change means you accept the
            updated terms.
          </p>
        </section>
      </div>
    </main>
  );
}
