import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

/** NSQF qualifications keyed by the lexicon's normalized skill tokens. */
const NSQF = [
  {
    qpCode: "AGR/Q0101",
    title: "Pottery Craftsperson (Wheel Thrown)",
    titleHindi: "मृद्भांड शिल्पकार",
    sector: "Handicrafts & Carpet",
    nsqfLevel: 4,
    ssc: "Handicrafts & Carpet SSC",
    keywords: ["pottery"],
  },
  {
    qpCode: "AMH/Q1947",
    title: "Self Employed Tailor",
    titleHindi: "स्वरोजगार दर्जी",
    sector: "Apparel, Made-ups & Home Furnishing",
    nsqfLevel: 4,
    ssc: "Apparel Made-ups & Home Furnishing SSC",
    keywords: ["tailoring", "embroidery"],
  },
  {
    qpCode: "HCS/Q7302",
    title: "Handloom Weaver (Frame Loom)",
    titleHindi: "हथकरघा बुनकर",
    sector: "Handloom",
    nsqfLevel: 4,
    ssc: "Handloom Sector SSC",
    keywords: ["handloom-weaving"],
  },
  {
    qpCode: "LSS/Q5301",
    title: "Footwear Maker (Hand Crafted)",
    titleHindi: "जूता निर्माता",
    sector: "Leather",
    nsqfLevel: 3,
    ssc: "Leather Sector Skill Council",
    keywords: ["leatherwork"],
  },
  {
    qpCode: "CON/Q0103",
    title: "Assistant Carpenter",
    titleHindi: "सहायक बढ़ई",
    sector: "Construction",
    nsqfLevel: 3,
    ssc: "Construction Skill Development Council",
    keywords: ["carpentry"],
  },
  {
    qpCode: "CON/Q0101",
    title: "Assistant Mason",
    titleHindi: "सहायक राजमिस्त्री",
    sector: "Construction",
    nsqfLevel: 3,
    ssc: "Construction Skill Development Council",
    keywords: ["masonry"],
  },
  {
    qpCode: "AGR/Q1101",
    title: "Organic Grower",
    titleHindi: "जैविक कृषक",
    sector: "Agriculture",
    nsqfLevel: 4,
    ssc: "Agriculture Skill Council of India",
    keywords: ["agriculture"],
  },
  {
    qpCode: "AGR/Q4102",
    title: "Dairy Farmer / Entrepreneur",
    titleHindi: "डेयरी किसान",
    sector: "Agriculture",
    nsqfLevel: 4,
    ssc: "Agriculture Skill Council of India",
    keywords: ["dairy-livestock"],
  },
  {
    qpCode: "BWS/Q0101",
    title: "Assistant Beauty Therapist",
    titleHindi: "सहायक ब्यूटी थेरेपिस्ट",
    sector: "Beauty & Wellness",
    nsqfLevel: 3,
    ssc: "Beauty & Wellness SSC",
    keywords: ["beautician"],
  },
  {
    qpCode: "FIC/Q0101",
    title: "Food & Vegetable Processing Technician",
    titleHindi: "खाद्य प्रसंस्करण तकनीशियन",
    sector: "Food Processing",
    nsqfLevel: 4,
    ssc: "Food Industry Capacity & Skill Initiative",
    keywords: ["food-processing"],
  },
  {
    qpCode: "PSS/Q0104",
    title: "Domestic Electrician",
    titleHindi: "घरेलू इलेक्ट्रीशियन",
    sector: "Electronics",
    nsqfLevel: 4,
    ssc: "Electronics Sector Skills Council",
    keywords: ["electrical"],
  },
  {
    qpCode: "PLM/Q0102",
    title: "Plumber (General)",
    titleHindi: "प्लंबर",
    sector: "Plumbing",
    nsqfLevel: 4,
    ssc: "Indian Plumbing Skills Council",
    keywords: ["plumbing"],
  },
  {
    qpCode: "CSC/Q0204",
    title: "Welder (Gas Metal Arc Welding)",
    titleHindi: "वेल्डर",
    sector: "Capital Goods",
    nsqfLevel: 4,
    ssc: "Capital Goods Skill Council",
    keywords: ["welding"],
  },
  {
    qpCode: "ELE/Q6002",
    title: "Field Technician - Mobile Phone",
    titleHindi: "मोबाइल फोन तकनीशियन",
    sector: "Electronics",
    nsqfLevel: 4,
    ssc: "Electronics Sector Skills Council",
    keywords: ["mobile-repair"],
  },
  {
    qpCode: "ASC/Q9703",
    title: "Commercial Vehicle Driver (Level 4)",
    titleHindi: "वाणिज्यिक वाहन चालक",
    sector: "Automotive",
    nsqfLevel: 4,
    ssc: "Automotive Skills Development Council",
    keywords: ["driving"],
  },
  {
    qpCode: "HCS/Q6501",
    title: "Cane & Bamboo Craftsperson",
    titleHindi: "बेंत एवं बांस शिल्पकार",
    sector: "Handicrafts & Carpet",
    nsqfLevel: 4,
    ssc: "Handicrafts & Carpet SSC",
    keywords: ["handicraft-bamboo"],
  },
  {
    qpCode: "DWC/Q0101",
    title: "Domestic Housekeeper",
    titleHindi: "घरेलू परिचारिका",
    sector: "Domestic Work",
    nsqfLevel: 3,
    ssc: "Domestic Workers Sector Skill Council",
    keywords: ["housekeeping"],
  },
  {
    qpCode: "HSS/Q5122",
    title: "General Duty Assistant (Home Health Aide)",
    titleHindi: "सामान्य ड्यूटी सहायक",
    sector: "Healthcare",
    nsqfLevel: 4,
    ssc: "Healthcare Sector Skill Council",
    keywords: ["healthcare-support"],
  },
  {
    qpCode: "RAS/Q0103",
    title: "Retail Sales Associate",
    titleHindi: "खुदरा बिक्री सहयोगी",
    sector: "Retail",
    nsqfLevel: 4,
    ssc: "Retailers Association's Skill Council of India",
    keywords: ["retail"],
  },
];

async function main() {
  console.log("Seeding NSQF qualifications…");
  const qualByKeyword = new Map<string, string>();
  for (const q of NSQF) {
    const rec = await prisma.nsqfQualification.upsert({
      where: { qpCode: q.qpCode },
      update: q,
      create: q,
    });
    for (const k of q.keywords) qualByKeyword.set(k, rec.id);
  }

  console.log("Seeding PM-AJAY training programmes…");
  const programs = [
    {
      name: "PM-AJAY Skill Development — Pottery & Terracotta, Khurja",
      nameHindi: "पीएम-अजय कौशल विकास — मृद्भांड, खुर्जा",
      component: "Skill Development",
      providerName: "District Rural Development Agency, Bulandshahr",
      keyword: "pottery",
      sector: "Handicrafts & Carpet",
      nsqfLevel: 4,
      mode: "OFFLINE",
      durationWeeks: 12,
      stipend: true,
      certification: "NSQF Level 4 (NSDC)",
      state: "Uttar Pradesh",
      district: "Bulandshahr",
      contactPhone: "05732-000000",
      seatsTotal: 40,
      seatsAvailable: 12,
      eligibilityNote: "SC beneficiaries under PM-AJAY, age 18–45",
    },
    {
      name: "PM-AJAY GIA — Self Employed Tailoring Batch, Nagpur",
      nameHindi: "पीएम-अजय — स्वरोजगार सिलाई बैच, नागपुर",
      component: "GIA",
      providerName: "State SC Development Corporation, Maharashtra",
      keyword: "tailoring",
      sector: "Apparel, Made-ups & Home Furnishing",
      nsqfLevel: 4,
      mode: "OFFLINE",
      durationWeeks: 10,
      stipend: true,
      certification: "NSQF Level 4 (AMHSSC)",
      state: "Maharashtra",
      district: "Nagpur",
      contactPhone: "0712-000000",
      seatsTotal: 30,
      seatsAvailable: 8,
      eligibilityNote: "SC women prioritised; free tool-kit on completion",
    },
    {
      name: "PM-AJAY Adarsh Gram — Handloom Weaving Centre, Bhagalpur",
      nameHindi: "पीएम-अजय आदर्श ग्राम — हथकरघा केंद्र, भागलपुर",
      component: "Adarsh Gram",
      providerName: "Weavers Service Centre, Bhagalpur",
      keyword: "handloom-weaving",
      sector: "Handloom",
      nsqfLevel: 4,
      mode: "OFFLINE",
      durationWeeks: 16,
      stipend: true,
      certification: "NSQF Level 4 (HSSC)",
      state: "Bihar",
      district: "Bhagalpur",
      contactPhone: "0641-000000",
      seatsTotal: 25,
      seatsAvailable: 15,
      eligibilityNote: "Residents of PM-AJAY Adarsh Gram villages",
    },
    {
      name: "PM-AJAY Skill Development — Footwear & Leather, Agra",
      nameHindi: "पीएम-अजय — जूता एवं चर्म, आगरा",
      component: "Skill Development",
      providerName: "Footwear Design & Development Institute, Agra",
      keyword: "leatherwork",
      sector: "Leather",
      nsqfLevel: 3,
      mode: "HYBRID",
      durationWeeks: 8,
      stipend: false,
      certification: "NSQF Level 3 (LSSC)",
      state: "Uttar Pradesh",
      district: "Agra",
      contactPhone: "0562-000000",
      seatsTotal: 50,
      seatsAvailable: 22,
      eligibilityNote: "SC beneficiaries; placement linkage with local units",
    },
    {
      name: "PM-AJAY GIA — Assistant Mason & Carpenter, Jaipur",
      nameHindi: "पीएम-अजय — सहायक राजमिस्त्री एवं बढ़ई, जयपुर",
      component: "GIA",
      providerName: "CSDCI Accredited Centre, Jaipur",
      keyword: "masonry",
      sector: "Construction",
      nsqfLevel: 3,
      mode: "OFFLINE",
      durationWeeks: 6,
      stipend: true,
      certification: "NSQF Level 3 (CSDCI)",
      state: "Rajasthan",
      district: "Jaipur",
      contactPhone: "0141-000000",
      seatsTotal: 60,
      seatsAvailable: 30,
      eligibilityNote: "SC beneficiaries, age 18–50; on-site training",
    },
    {
      name: "PM-AJAY Skill Development — Dairy Entrepreneurship, Anand",
      nameHindi: "पीएम-अजय — डेयरी उद्यमिता, आणंद",
      component: "Skill Development",
      providerName: "Amul Dairy Training Centre, Anand",
      keyword: "dairy-livestock",
      sector: "Agriculture",
      nsqfLevel: 4,
      mode: "OFFLINE",
      durationWeeks: 4,
      stipend: false,
      certification: "NSQF Level 4 (ASCI)",
      state: "Gujarat",
      district: "Anand",
      contactPhone: "02692-000000",
      seatsTotal: 35,
      seatsAvailable: 18,
      eligibilityNote: "SC beneficiaries owning/leasing cattle; credit linkage",
    },
    {
      name: "PM-AJAY GIA — Beauty & Wellness Batch, Lucknow",
      nameHindi: "पीएम-अजय — ब्यूटी एवं वेलनेस, लखनऊ",
      component: "GIA",
      providerName: "B&WSSC Accredited Centre, Lucknow",
      keyword: "beautician",
      sector: "Beauty & Wellness",
      nsqfLevel: 3,
      mode: "OFFLINE",
      durationWeeks: 8,
      stipend: true,
      certification: "NSQF Level 3 (B&WSSC)",
      state: "Uttar Pradesh",
      district: "Lucknow",
      contactPhone: "0522-000000",
      seatsTotal: 30,
      seatsAvailable: 9,
      eligibilityNote: "SC women prioritised; salon placement support",
    },
    {
      name: "PM-AJAY Skill Development — Food Processing (Pickles & Papad), Bhopal",
      nameHindi: "पीएम-अजय — खाद्य प्रसंस्करण, भोपाल",
      component: "Skill Development",
      providerName: "FICSI Accredited Centre, Bhopal",
      keyword: "food-processing",
      sector: "Food Processing",
      nsqfLevel: 4,
      mode: "OFFLINE",
      durationWeeks: 6,
      stipend: true,
      certification: "NSQF Level 4 (FICSI)",
      state: "Madhya Pradesh",
      district: "Bhopal",
      contactPhone: "0755-000000",
      seatsTotal: 40,
      seatsAvailable: 25,
      eligibilityNote: "SC SHG members prioritised; FSSAI registration support",
    },
    {
      name: "PM-AJAY GIA — Domestic Electrician, Hyderabad",
      nameHindi: "पीएम-अजय — घरेलू इलेक्ट्रीशियन, हैदराबाद",
      component: "GIA",
      providerName: "ESSCI Accredited Centre, Hyderabad",
      keyword: "electrical",
      sector: "Electronics",
      nsqfLevel: 4,
      mode: "OFFLINE",
      durationWeeks: 10,
      stipend: true,
      certification: "NSQF Level 4 (ESSCI)",
      state: "Telangana",
      district: "Hyderabad",
      contactPhone: "040-00000000",
      seatsTotal: 45,
      seatsAvailable: 20,
      eligibilityNote: "SC beneficiaries, min. class 8; wage-employment linkage",
    },
    {
      name: "PM-AJAY Skill Development — Mobile Phone Repair, Patna",
      nameHindi: "पीएम-अजय — मोबाइल रिपेयर, पटना",
      component: "Skill Development",
      providerName: "ESSCI Accredited Centre, Patna",
      keyword: "mobile-repair",
      sector: "Electronics",
      nsqfLevel: 4,
      mode: "HYBRID",
      durationWeeks: 8,
      stipend: false,
      certification: "NSQF Level 4 (ESSCI)",
      state: "Bihar",
      district: "Patna",
      contactPhone: "0612-000000",
      seatsTotal: 40,
      seatsAvailable: 28,
      eligibilityNote: "SC youth, age 18–35; self-employment tool-kit",
    },
    {
      name: "PM-AJAY GIA — Cane & Bamboo Craft, Guwahati",
      nameHindi: "पीएम-अजय — बेंत एवं बांस शिल्प, गुवाहाटी",
      component: "GIA",
      providerName: "Cane & Bamboo Technology Centre, Guwahati",
      keyword: "handicraft-bamboo",
      sector: "Handicrafts & Carpet",
      nsqfLevel: 4,
      mode: "OFFLINE",
      durationWeeks: 12,
      stipend: true,
      certification: "NSQF Level 4 (HCSSC)",
      state: "Assam",
      district: "Kamrup Metropolitan",
      contactPhone: "0361-000000",
      seatsTotal: 30,
      seatsAvailable: 14,
      eligibilityNote: "SC artisans; market linkage with SFURTI cluster",
    },
    {
      name: "PM-AJAY Skill Development — General Duty Assistant, Delhi",
      nameHindi: "पीएम-अजय — सामान्य ड्यूटी सहायक, दिल्ली",
      component: "Skill Development",
      providerName: "HSSC Accredited Centre, New Delhi",
      keyword: "healthcare-support",
      sector: "Healthcare",
      nsqfLevel: 4,
      mode: "OFFLINE",
      durationWeeks: 14,
      stipend: true,
      certification: "NSQF Level 4 (HSSC)",
      state: "Delhi",
      district: "New Delhi",
      contactPhone: "011-00000000",
      seatsTotal: 50,
      seatsAvailable: 19,
      eligibilityNote: "SC beneficiaries, class 10 pass; hospital placement",
    },
  ];

  for (const p of programs) {
    const { keyword, ...rest } = p;
    await prisma.trainingProgram.upsert({
      where: { id: slug(p.name) },
      update: { ...rest, nsqfQualificationId: qualByKeyword.get(keyword) ?? null },
      create: {
        id: slug(p.name),
        ...rest,
        nsqfQualificationId: qualByKeyword.get(keyword) ?? null,
      },
    });
  }

  console.log("Seeding demo users…");
  await prisma.user.upsert({
    where: { phone: "9999900000" },
    update: {},
    create: {
      phone: "9999900000",
      name: "Admin (MoSJE)",
      role: "ADMIN",
      passwordHash: await bcrypt.hash("admin123", 10),
      language: "en",
    },
  });
  await prisma.user.upsert({
    where: { phone: "9000000001" },
    update: {},
    create: {
      phone: "9000000001",
      name: "Ramesh (demo beneficiary)",
      role: "BENEFICIARY",
      passwordHash: await bcrypt.hash("demo123", 10),
      language: "hi",
      category: "SC",
      state: "Uttar Pradesh",
      district: "Bulandshahr",
    },
  });

  console.log("Done.");
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 60);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
